export interface MealDay {
  date: string;
  icon: string;
  type: 'Gris' | 'Okse' | 'Fjerkræ' | 'Fisk' | 'Grøn' | 'Fest';
  dish: string;       // Hovedret navn
  protein: string;    // Kød/Fisk mængde (90-110g)
  sauce: string;      // Sauce mængde (1 dl)
  carb: string;       // Kartofler/Ris (100g)
  veg: string;        // Grønt (30-50g)
  biret: string;      // Suppe/Dessert/Kage
  isHoliday?: boolean;
}

export interface ALaCarteItem {
  id: number;
  category: 'Hovedret' | 'Suppe' | 'Dessert';
  name: string;
  description: string;
}

// --- A LA CARTE MENU (Fixed assortment jf. MDS Contract) ---
// Contract Rules:
// - Soup is always "Dagens suppe" (the day's soup), never specific soups like Asparagus
// - Desserts should be popular dishes from the monthly menu
// - No repetition from previous months
// - Must include popular items: Citronfromage, Rabarberkage, Chokolademousse
//
// PORTION STANDARDS (MANDATORY):
// - Meat + Sauce together: 80g meat + 100g sauce
// - Meatballs in curry ("boller i karry") or meatballs ("frikadeller"): preferably 3 pieces of 30-40g each
// - Cooked potatoes: 100g
// - Rice: 100g
// - Pasta: 100g
// - Rye bread: 1 piece
// - Pickled vegetables: 25g
// - Green salad: 30g
// - Raw vegetables: 35g
// - Steamed/fried/boiled vegetables: 50g
// - Creamy salads (coleslaw, waldorf, etc.): 50g
// - Sauce (general): 100g
// - Stew: 100g sauce + 50g vegetables
// - Creamed potatoes: 100g potatoes + 40g cream
// - Porridge: 125g + 25g cream
// - Rice pudding: 250g
// - Cream/dressings (remoulade, tartar, chili mayo, etc.): 80g
export const aLaCarteMenu: ALaCarteItem[] = [
  { id: 1, category: 'Hovedret', name: 'Kalvegryde i flødesauce', description: 'Af kalv (180g ret) med kartofler, gulerødder og flødesauce.' },
  { id: 2, category: 'Hovedret', name: 'Svinekølle i flødesauce', description: 'Med persillesauce, kogte kartofler og rødbeder.' },
  { id: 3, category: 'Hovedret', name: 'Frikadeller', description: 'M. kartofler, brun sauce og surt.' },
  { id: 4, category: 'Hovedret', name: 'Karbonader', description: 'Med stuvede ærter og gulerødder samt kartofler.' },
  { id: 21, category: 'Suppe', name: 'Dagens suppe', description: 'Suppe efter sæson (150g).' },
  { id: 22, category: 'Suppe', name: 'Dagens frugtgrød', description: 'Frugtgrød med fløde (150g).' },
  { id: 23, category: 'Dessert', name: 'Citronfromage', description: 'M. skum (90g).' },
  { id: 24, category: 'Dessert', name: 'Rabarberkage', description: 'M. crumble (90g).' },
  { id: 25, category: 'Dessert', name: 'Chokolademousse', description: 'M. flødeskum (90g).' },
];

// ================== JANUAR 2026 ==================
export const january2026: MealDay[] = [
  { date: "1. jan (Tor)", icon: "🐂", type: "Okse", dish: "Lasagne m. kødsauce", protein: "90g Kød", sauce: "Tomat/Bechamel", carb: "Brød (1 stk)", veg: "Råkost", biret: "Fløderand m. frugt (90g)", isHoliday: true },
  { date: "2. jan (Fre)", icon: "🥦", type: "Grøn", dish: "Chili sin carne", protein: "Vegetar/Bønner", sauce: "Tomatsauce", carb: "Ris", veg: "Creme fraiche", biret: "Ost og Sprød (60g)" },
  { date: "3. jan (Lør)", icon: "🐓", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g", sauce: "Aspargessauce", carb: "Tarteletter (2 stk)", veg: "Tomat/Persille", biret: "Chokoladekage (70g)" },
  { date: "4. jan (Søn)", icon: "🐂", type: "Okse", dish: "Gl.dags Rullesteg", protein: "90g", sauce: "Skysauce", carb: "Kartofler", veg: "Rødbeder", biret: "Rødgrød m. fløde (150g)", isHoliday: true },
  { date: "5. jan (Man)", icon: "🐖", type: "Gris", dish: "Skipperlabskovs", protein: "250g", sauce: "(I retten)", carb: "Rugbrød (1 sk)", veg: "Rødbeder", biret: "Gulerodssuppe (150g)" },
  { date: "6. jan (Tir)", icon: "🐓", type: "Fjerkræ", dish: "Sprængt kylling", protein: "90g", sauce: "Flødesauce", carb: "Kartofler", veg: "Rabarberkompot", biret: "Æblekompot m. skum (90g)" },
  { date: "7. jan (Ons)", icon: "🐟", type: "Fisk", dish: "Bagte ørred", protein: "90g", sauce: "Spinatcreme", carb: "Kartofler", veg: "Rødløg", biret: "Pannacotta (90g)" },
  { date: "8. jan (Tor)", icon: "🥦", type: "Grøn", dish: "Pastinakpostej", protein: "110g", sauce: "Ratatouille", carb: "Kartofler", veg: "Sylt. agurker", biret: "Græskarsuppe (150g)" },
  { date: "9. jan (Fre)", icon: "🐖", type: "Gris", dish: "Pølse m. krydderurt", protein: "110g", sauce: "Løgsovs", carb: "Kartoffelmos", veg: "Ærter", biret: "Drømmekage (70g)" },
  { date: "10. jan (Lør)", icon: "🐓", type: "Fjerkræ", dish: "Paprikagryde", protein: "180g", sauce: "Paprikasauce", carb: "Ris", veg: "Persille", biret: "Frugtsalat m. creme (100g)" },
  { date: "11. jan (Søn)", icon: "🐂", type: "Okse", dish: "Oksesteg", protein: "90g", sauce: "Portvinssauce", carb: "Flødekartofler", veg: "Ærter", biret: "Gulerodskage (70g)", isHoliday: true },
  { date: "12. jan (Man)", icon: "🐖", type: "Gris", dish: "Boller i karry", protein: "3stk/90g", sauce: "Karrysauce", carb: "Ris", veg: "Rabarberchutney", biret: "Ost m. knækbrød (60g)" },
  { date: "13. jan (Tir)", icon: "🐟", type: "Fisk", dish: "Paneret fisk", protein: "90g", sauce: "Remoulade", carb: "Stegte kart.", veg: "Citron", biret: "Jordbærgrød m. fløde (150g)" },
  { date: "14. jan (Ons) 👑", icon: "🐖", type: "Gris", dish: "Kongens Livret: Stegt flæsk", protein: "90g", sauce: "Persillesauce", carb: "Kartofler", veg: "Rødbeder", biret: "Kongekage (70g)", isHoliday: true },
  { date: "15. jan (Tor)", icon: "🥦", type: "Grøn", dish: "Pennepasta", protein: "Vegetar", sauce: "Svampesovs", carb: "Pasta", veg: "Løgdrys", biret: "Tomatsuppe (150g)" },
  { date: "16. jan (Fre)", icon: "🐖", type: "Gris", dish: "Hjerter i fløde", protein: "150g", sauce: "Flødesauce", carb: "Kartoffelmos", veg: "Spinatsalat", biret: "Sandkage (70g)" },
  { date: "17. jan (Lør)", icon: "🐓", type: "Fjerkræ", dish: "BBQ Kylling", protein: "90g", sauce: "BBQ sauce", carb: "Kartofler", veg: "Spidskål", biret: "Hindbærstrifli (90g)" },
  { date: "18. jan (Søn)", icon: "🐂", type: "Okse", dish: "Nakkesteg", protein: "90g", sauce: "Estragonsauce", carb: "Kartoffelmos", veg: "Bagte grønt", biret: "Henkogt frugt (90g)", isHoliday: true },
  { date: "19. jan (Man)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2 stk/90g", sauce: "Stuvede kål", carb: "Kartofler", veg: "Syl. Rødløg", biret: "Cremet gulerodssuppe" },
  { date: "20. jan (Tir)", icon: "🐓", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g", sauce: "Cremet sauce", carb: "Ris", veg: "Broccoli", biret: "Cremelinser (70g)" },
  { date: "21. jan (Ons)", icon: "🐟", type: "Fisk", dish: "Fisk i sellerisalat", protein: "180g", sauce: "Sennepsauce", carb: "Kartofler", veg: "Citron", biret: "Budding m. saft (110g)" },
  { date: "22. jan (Tor)", icon: "🥦", type: "Grøn", dish: "Porretærte", protein: "160g", sauce: "Chili dressing", carb: "-", veg: "Tomatsalat", biret: "Minestrone (150g)" },
  { date: "23. jan (Fre)", icon: "🐖", type: "Gris", dish: "Forloren hare", protein: "90g", sauce: "Vildtsauce", carb: "Kartofler", veg: "Valnøddesalat", biret: "Kokostoppe (60g)" },
  { date: "24. jan (Lør)", icon: "🐓", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g", sauce: "Aspargessauce", carb: "Tarteletter", veg: "Tomatsalat", biret: "Æblegrød (150g)" },
  { date: "25. jan (Søn)", icon: "🐂", type: "Okse", dish: "Oksesteg", protein: "90g", sauce: "Rødvinssauce", carb: "Flødekartofler", veg: "Gulerødder", biret: "Tiramisu (75g)", isHoliday: true },
  { date: "26. jan (Man)", icon: "🐖", type: "Gris", dish: "Krebinet", protein: "1 stk/110g", sauce: "Stuvning", carb: "Kartofler", veg: "Persille", biret: "Hyldebærsuppe m. æbler" },
  { date: "27. jan (Tir)", icon: "🐓", type: "Fjerkræ", dish: "Chicken Tikka", protein: "180g", sauce: "Masalasauce", carb: "Ris", veg: "Tzatziki", biret: "Frugtsalat (110g)" },
  { date: "28. jan (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt fisk", protein: "90g", sauce: "Hvidvinssauce", carb: "Kartofler", veg: "Grøntsager", biret: "Panna cotta m. passion" },
  { date: "29. jan (Tor)", icon: "🥦", type: "Grøn", dish: "Gulerodsgratin", protein: "160g", sauce: "Smør", carb: "Rugbrød", veg: "Tomater", biret: "Blomkålssuppe (150g)" },
  { date: "30. jan (Fre)", icon: "🐖", type: "Gris", dish: "Frikassé", protein: "180g", sauce: "Frikassésauce", carb: "Kartofler", veg: "Ærter", biret: "Gl.dags æblekage (90g)" },
  { date: "31. jan (Lør)", icon: "🐓", type: "Fjerkræ", dish: "Spansk æggekage", protein: "150g", sauce: "-", carb: "Rugbrød", veg: "Grønsalat", biret: "Citronfromage (90g)" },
];

export const february2026: MealDay[] = [
  { date: "1. feb (Søn)", icon: "🐂", type: "Okse", dish: "Gl.dags Oksesteg", protein: "90g", sauce: "Peberrodssauce", carb: "Kartofler", veg: "Bønner", biret: "Citronfromage (90g)", isHoliday: true },
  { date: "2. feb (Man)", icon: "🐖", type: "Gris", dish: "Mørbradgryde", protein: "180g", sauce: "Paprikasauce", carb: "Ris", veg: "Cocktailpølser", biret: "Minestronesuppe (150g)" },
  { date: "3. feb (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Karry", protein: "180g", sauce: "Karrysauce", carb: "Løse Ris", veg: "Mango chutney", biret: "Chokoladekage (70g)" },
  { date: "4. feb (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred", protein: "90g", sauce: "Sennepsauce", carb: "Kartofler", veg: "Rødbedetern", biret: "Rabarbertrifli (90g)" },
  { date: "5. feb (Tor)", icon: "🥦", type: "Grøn", dish: "Grøntsagslasagne", protein: "200g", sauce: "Tomat/Bechamel", carb: "(Pasta i ret)", veg: "Tomatsalat", biret: "Kartoffel-porresuppe (150g)" },
  { date: "6. feb (Fre)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2stk/90g", sauce: "Brun sauce", carb: "Kartofler", veg: "Surkål", biret: "Drømmekage (70g)" },
  { date: "7. feb (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g", sauce: "Aspargessauce", carb: "Tarteletter (2stk)", veg: "Persille/Tomat", biret: "Frugtsalat m. creme (100g)" },
  { date: "8. feb (Søn)", icon: "🐂", type: "Okse", dish: "Kalvesteg", protein: "90g", sauce: "Vildtsauce", carb: "Kartofler", veg: "Waldorfsalat", biret: "Karamelrand (90g)", isHoliday: true },
  { date: "9. feb (Man)", icon: "🐖", type: "Gris", dish: "Brændende Kærlighed", protein: "200g", sauce: "(Fedtstof i mos)", carb: "Kartoffelmos", veg: "Bacon/Løg", biret: "Tomatsuppe (150g)" },
  { date: "10. feb (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Unghanebryst", protein: "90g", sauce: "Skysauce", carb: "Kartofler", veg: "Agurkesalat", biret: "Gulerodskage (70g)" },
  { date: "11. feb (Ons)", icon: "🥦", type: "Grøn", dish: "Porretærte", protein: "150g", sauce: "Cremefraiche", carb: "-", veg: "Tomatsalat", biret: "Aspargessuppe (150g)" },
  { date: "12. feb (Tor)", icon: "🐟", type: "Fisk", dish: "Ovnbagt Ørred", protein: "90g", sauce: "Citronsauce", carb: "Kartofler", veg: "Spinat", biret: "Romfromage (90g)" },
  { date: "13. feb (Fre)", icon: "🐖", type: "Gris", dish: "Skinke m. flødekart.", protein: "90g", sauce: "(Fløde i kart.)", carb: "Flødekartofler", veg: "Grønne bønner", biret: "Banankage (70g)" },
  { date: "14. feb (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingeboller i karry", protein: "90g", sauce: "Karrysauce", carb: "Ris", veg: "Chutney", biret: "Sveskegrød m. fløde (150g)" },
  { date: "15. feb (Søn) 🎭", icon: "🐂", type: "Okse", dish: "Fastelavn: Bankekød", protein: "90g", sauce: "Brun sauce", carb: "Kartoffelmos", veg: "Laurbærblade", biret: "Fastelavnsbolle (1 stk)", isHoliday: true },
  { date: "16. feb (Man)", icon: "🐖", type: "Gris", dish: "Svensk Pølseret", protein: "200g", sauce: "Tomat/Fløde", carb: "Kartofler", veg: "Purløg", biret: "Blomkålssuppe (150g)" },
  { date: "17. feb (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingefrikassé", protein: "180g", sauce: "Frikassésauce", carb: "Kartofler", veg: "Ærter/Gulerød.", biret: "Citronmåne (70g)" },
  { date: "18. feb (Ons)", icon: "🐟", type: "Fisk", dish: "Fiskefrikadeller", protein: "2stk/90g", sauce: "Remoulade", carb: "Kartofler", veg: "Citron", biret: "Budding m. saft (100g)" },
  { date: "19. feb (Tor)", icon: "🥦", type: "Grøn", dish: "Blomkålsgratin", protein: "160g", sauce: "Smeltet smør", carb: "Rugbrød (1sk)", veg: "Gulerodssalat", biret: "Klar suppe m. boller (150g)" },
  { date: "20. feb (Fre)", icon: "🐖", type: "Gris", dish: "Karbonader", protein: "1stk/110g", sauce: "Stuvede ærter", carb: "Kartofler", veg: "Gulerødder", biret: "Sandkage (70g)" },
  { date: "21. feb (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Paprikagryde (Kyl)", protein: "180g", sauce: "Paprikasauce", carb: "Ris", veg: "Persille", biret: "Jordbærgrød m. fløde (150g)" },
  { date: "22. feb (Søn)", icon: "🐂", type: "Okse", dish: "Benløse Fugle", protein: "2stk/90g", sauce: "Skysauce", carb: "Kartoffelmos", veg: "Tyttebær", biret: "Sherryfromage (90g)", isHoliday: true },
  { date: "23. feb (Man)", icon: "🐖", type: "Gris", dish: "Boller i Selleri", protein: "3stk/90g", sauce: "Sellerisauce", carb: "Kartofler", veg: "Persille", biret: "Minestronesuppe (150g)" },
  { date: "24. feb (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Sprængt Kylling", protein: "90g", sauce: "Peberrodssauce", carb: "Kartofler", veg: "Gulerødder", biret: "Kage m. creme (70g)" },
  { date: "25. feb (Ons)", icon: "🥦", type: "Grøn", dish: "Ovnæggekage", protein: "150g", sauce: "-", carb: "Rugbrød (1sk)", veg: "Tomat/Purløg", biret: "Grøntsagssuppe (150g)" },
  { date: "26. feb (Tor)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g", sauce: "Persillesauce", carb: "Kartofler", veg: "Citron", biret: "Fersken m. fløde (100g)" },
  { date: "27. feb (Fre)", icon: "🐖", type: "Gris", dish: "Forloren Hare", protein: "90g", sauce: "Vildtsauce", carb: "Kartofler", veg: "Ribsgelé", biret: "Hindbærsnitte (60g)" },
  { date: "28. feb (Lør)", icon: "🐂", type: "Okse", dish: "Hakkebøf", protein: "90g", sauce: "Brun sauce", carb: "Kartofler", veg: "Bløde løg", biret: "Pæretærte (90g)" },
];

export const march2026: MealDay[] = [
  { date: "1. mar (Søn)", icon: "🐂", type: "Okse", dish: "Bankekød", protein: "90g Kød", sauce: "Sky", carb: "Mos", veg: "Laurbær", biret: "Frugtgrød (150g)", isHoliday: true },
  { date: "2. mar (Man)", icon: "🐖", type: "Gris", dish: "Biksemad", protein: "Kødtern", sauce: "Bearnaise", carb: "-", veg: "Rødbeder", biret: "Appelsinsuppe (150g)" },
  { date: "3. mar (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Karry", protein: "90g Kød", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Krydderkage (70g)" },
  { date: "4. mar (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred (Vejle)", protein: "90g Fisk", sauce: "Urtecreme", carb: "Kartofler", veg: "Dild", biret: "Pæretærte (90g)" },
  { date: "5. mar (Tor)", icon: "🥦", type: "Grøn", dish: "Gule Ærter", protein: "Flæsk", sauce: "-", carb: "-", veg: "Sennep", biret: "Pandekager (2 stk)" },
  { date: "6. mar (Fre)", icon: "🐖", type: "Gris", dish: "Mørbradbøf", protein: "90g Kød", sauce: "Champignon", carb: "Kartofler", veg: "Løg", biret: "Sandkage (70g)" },
  { date: "7. mar (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Andebryst", protein: "90g And", sauce: "Sky", carb: "Kartofler", veg: "Svesker", biret: "Risengrød (150g)" },
  { date: "8. mar (Søn)", icon: "🐂", type: "Okse", dish: "Wienerschnitzel", protein: "110g Kalv", sauce: "Smør", carb: "Brasede", veg: "Ærter", biret: "Rubinsteinerkage (70g)", isHoliday: true },
  { date: "9. mar (Man)", icon: "🐖", type: "Gris", dish: "Koteletter i fad", protein: "110g Kød", sauce: "Tomat/Fløde", carb: "Ris", veg: "-", biret: "Karrysuppe (150g)" },
  { date: "10. mar (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g Ret", sauce: "Fløde", carb: "Mos", veg: "Gulerødder", biret: "Gulerodskage (70g)" },
  { date: "11. mar (Ons)", icon: "🐟", type: "Fisk", dish: "Bagt Ørred (Vejle)", protein: "90g Fisk", sauce: "Mandel", carb: "Kartofler", veg: "Grønt", biret: "Frugtsalat (100g)" },
  { date: "12. mar (Tor)", icon: "🥦", type: "Grøn", dish: "Spinattærte", protein: "150g Ret", sauce: "-", carb: "-", veg: "Tomat", biret: "Kartoffel-porresuppe (150g)" },
  { date: "13. mar (Fre)", icon: "🐖", type: "Gris", dish: "Stegt Flæsk", protein: "90g Kød", sauce: "Persille", carb: "Kartofler", veg: "Rødbeder", biret: "Æblekage (90g)" },
  { date: "14. mar (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g Ret", sauce: "Asparges", carb: "Tarteletter", veg: "Persille", biret: "Sveskegrød (150g)" },
  { date: "15. mar (Søn)", icon: "🐂", type: "Okse", dish: "Kalvesteg", protein: "90g Kød", sauce: "Sky", carb: "Kartofler", veg: "Waldorf", biret: "Citronfromage (90g)", isHoliday: true },
  { date: "16. mar (Man)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2 stk", sauce: "Brun sauce", carb: "Kartofler", veg: "Surkål", biret: "Blomkålssuppe (150g)" },
  { date: "17. mar (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Peberrod", protein: "180g Ret", sauce: "Peberrod", carb: "Kartofler", veg: "Gulerødder", biret: "Citronmåne (70g)" },
  { date: "18. mar (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred", protein: "90g Fisk", sauce: "Urtecreme", carb: "Kartofler", veg: "Dild", biret: "Chokolademousse (80g)" },
  { date: "19. mar (Tor)", icon: "🥦", type: "Grøn", dish: "Ovnæggekage", protein: "150g Ret", sauce: "-", carb: "Rugbrød", veg: "Tomat", biret: "Minestronesuppe (150g)" },
  { date: "20. mar (Fre)", icon: "🐖", type: "Gris", dish: "Forloren Hare", protein: "110g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Tyttebær", biret: "Drømmekage (70g)" },
  { date: "21. mar (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingelår BBQ", protein: "1 stk", sauce: "BBQ", carb: "Kartofler", veg: "Coleslaw", biret: "Abrikosgrød (150g)" },
  { date: "22. mar (Søn)", icon: "🐂", type: "Okse", dish: "Oksesteg", protein: "90g Kød", sauce: "Rødvin", carb: "Flødekart.", veg: "Perleløg", biret: "Ymerfromage (90g)", isHoliday: true },
  { date: "23. mar (Man)", icon: "🐖", type: "Gris", dish: "Boller i Karry", protein: "3 stk", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Tomatsuppe (150g)" },
  { date: "24. mar (Tir)", icon: "🐖", type: "Gris", dish: "Karbonader", protein: "1 stk", sauce: "Stuvede ærter", carb: "Kartofler", veg: "Gulerød", biret: "Budding (100g)" },
  { date: "25. mar (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g Fisk", sauce: "Persillesauce", carb: "Kartofler", veg: "Citron", biret: "Jordbærgrød (150g)" },
  { date: "26. mar (Tor)", icon: "🥦", type: "Grøn", dish: "Broccoligratin", protein: "160g Ret", sauce: "-", carb: "Brød", veg: "Gulerodssalat", biret: "Klar suppe (150g)" },
  { date: "27. mar (Fre)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingefrikassé", protein: "180g Ret", sauce: "Frikassé", carb: "Kartofler", veg: "Grønt", biret: "Chokoladekage (70g)" },
  { date: "28. mar (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Tarteletter m. høns", protein: "2 stk", sauce: "Asparges", carb: "Tarteletter", veg: "Tomat", biret: "Frugtsalat (100g)" },
  { date: "29. mar (Søn)", icon: "🐂", type: "Okse", dish: "PALMESØN: Lammekølle", protein: "90g Kød", sauce: "Sky", carb: "Flødekart.", veg: "Bønner", biret: "Rabarbertrifli (90g)", isHoliday: true },
  { date: "30. mar (Man)", icon: "🐖", type: "Gris", dish: "Krebinet", protein: "1 stk", sauce: "Stuvning", carb: "Kartofler", veg: "Gulerødder", biret: "Aspargessuppe (150g)" },
  { date: "31. mar (Tir)", icon: "🐂", type: "Okse", dish: "Hakkebøf", protein: "90g Kød", sauce: "Bearnaise", carb: "Frites", veg: "Salat", biret: "Citronfromage (90g)" },
];

export const april2026: MealDay[] = [
  { date: "1. apr (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred (Vejle)", protein: "90g Fisk", sauce: "Sennep", carb: "Kartofler", veg: "Rødbedetern", biret: "Citronfromage (90g)" },
  { date: "2. apr (Tor)", icon: "🐂", type: "Okse", dish: "SKÆRTORSDAG: Lammesteg", protein: "90g Kød", sauce: "Sky", carb: "Flødekart.", veg: "Bønner", biret: "Hønsekødssuppe (150g)", isHoliday: true },
  { date: "3. apr (Fre)", icon: "🐟", type: "Fisk", dish: "LANGFREDAG: Ovnbagt Ørred", protein: "90g Fisk", sauce: "Hollandaise", carb: "Kartofler", veg: "Broccoli", biret: "Påskekage (70g)", isHoliday: true },
  { date: "4. apr (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i asparges", protein: "110g Ret", sauce: "Asparges", carb: "Tarteletter", veg: "Persille", biret: "Frugtsalat m. creme (100g)" },
  { date: "5. apr (Søn)", icon: "🐂", type: "Okse", dish: "PÅSKEDAG: Kalvesteg", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Waldorf", biret: "Rubinsteinerkage (70g)", isHoliday: true },
  { date: "6. apr (Man)", icon: "🐖", type: "Gris", dish: "2. PÅSKEDAG: Ribbensteg", protein: "90g Kød", sauce: "Brun sauce", carb: "Kartofler", veg: "Rødkål", biret: "Karrysuppe (150g)", isHoliday: true },
  { date: "7. apr (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Unghanebryst", protein: "90g Kød", sauce: "Sky", carb: "Kartofler", veg: "Agurkesalat", biret: "Gulerodskage (70g)" },
  { date: "8. apr (Ons)", icon: "🐟", type: "Fisk", dish: "Ovnbagt Ørred (Vejle)", protein: "90g Fisk", sauce: "Hvidvin", carb: "Kartofler", veg: "Broccoli", biret: "Frugtgrød m. fløde (150g)" },
  { date: "9. apr (Tor)", icon: "🥦", type: "Grøn", dish: "Porretærte", protein: "150g Ret", sauce: "-", carb: "-", veg: "Tomatsalat", biret: "Tomatsuppe (150g)" },
  { date: "10. apr (Fre)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2 stk", sauce: "Brun sauce", carb: "Kartofler", veg: "Surkål", biret: "Gl.dags Æblekage (90g)" },
  { date: "11. apr (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingeboller i karry", protein: "90g Kød", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Sveskegrød (150g)" },
  { date: "12. apr (Søn)", icon: "🐂", type: "Okse", dish: "Benløse Fugle", protein: "90g Kød", sauce: "Vildt", carb: "Kartoffelmos", veg: "Tyttebær", biret: "Budding m. saft (100g)", isHoliday: true },
  { date: "13. apr (Man)", icon: "🐖", type: "Gris", dish: "Svensk Pølseret", protein: "200g Ret", sauce: "-", carb: "Kartofler", veg: "Purløg", biret: "Blomkålssuppe (150g)" },
  { date: "14. apr (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g Ret", sauce: "Flødesauce", carb: "Ris", veg: "Ærter", biret: "Chokoladekage (70g)" },
  { date: "15. apr (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g Fisk", sauce: "Persillesauce", carb: "Kartofler", veg: "Citron", biret: "Henkogte pærer (100g)" },
  { date: "16. apr (Tor)", icon: "🥦", type: "Grøn", dish: "Grøntsagslasagne", protein: "200g Ret", sauce: "-", carb: "Brød", veg: "Råkost", biret: "Minestronesuppe (150g)" },
  { date: "17. apr (Fre)", icon: "🐖", type: "Gris", dish: "Karbonader", protein: "1 stk", sauce: "Stuvede ærter", carb: "Kartofler", veg: "Gulerødder", biret: "Citronmåne (70g)" },
  { date: "18. apr (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Sprængt Kylling", protein: "90g Kød", sauce: "Peberrodssauce", carb: "Kartofler", veg: "Grøntsager", biret: "Frugtsalat (100g)" },
  { date: "19. apr (Søn)", icon: "🐂", type: "Okse", dish: "Hakkebøf", protein: "90g Kød", sauce: "Brun sauce", carb: "Kartofler", veg: "Bløde løg", biret: "Jordbærgrød m. fløde (150g)", isHoliday: true },
  { date: "20. apr (Man)", icon: "🐖", type: "Gris", dish: "Boller i Selleri", protein: "90g Kød", sauce: "Sellerisauce", carb: "Kartofler", veg: "Persille", biret: "Aspargessuppe (150g)" },
  { date: "21. apr (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Paprika", protein: "180g Ret", sauce: "Paprika", carb: "Ris", veg: "Peberfrugt", biret: "Banankage (70g)" },
  { date: "22. apr (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred", protein: "90g Fisk", sauce: "Hvidvinssauce", carb: "Kartofler", veg: "Broccoli", biret: "Rabarberkompot (90g)" },
  { date: "23. apr (Tor)", icon: "🥦", type: "Grøn", dish: "Blomkålsgratin", protein: "160g Ret", sauce: "-", carb: "Rugbrød", veg: "Tomat", biret: "Klar suppe m. boller (150g)" },
  { date: "24. apr (Fre)", icon: "🐖", type: "Gris", dish: "Glaseret Skinke", protein: "90g Kød", sauce: "Flødesauce", carb: "Kartofler", veg: "Grønne bønner", biret: "Hindbærsnitte (60g)" },
  { date: "25. apr (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g Ret", sauce: "-", carb: "Tarteletter", veg: "Tomat", biret: "Sveskemos (100g)" },
  { date: "26. apr (Søn)", icon: "🐂", type: "Okse", dish: "Oksesteg", protein: "90g Kød", sauce: "Rødvinssauce", carb: "Kartofler", veg: "Glas. perleløg", biret: "Citronfromage (90g)", isHoliday: true },
  { date: "27. apr (Man)", icon: "🐖", type: "Gris", dish: "Farseret Porre", protein: "1 stk", sauce: "Skysauce", carb: "Kartofler", veg: "Gulerødder", biret: "Kartoffelsuppe (150g)" },
  { date: "28. apr (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingefrikassé", protein: "180g Ret", sauce: "Frikassé", carb: "Kartofler", veg: "Ærter", biret: "Brunsviger (70g)" },
  { date: "29. apr (Ons)", icon: "🐟", type: "Fisk", dish: "Bagt Ørred (Vejle)", protein: "90g Fisk", sauce: "Urtecreme", carb: "Kartofler", veg: "Dild", biret: "Frugtgrød (150g)" },
  { date: "30. apr (Tor)", icon: "🥦", type: "Grøn", dish: "Ovnæggekage", protein: "150g Ret", sauce: "-", carb: "Rugbrød", veg: "Tomat/Purløg", biret: "Grøntsagssuppe (150g)" },
];

export const may2026: MealDay[] = [
  { date: "1. maj (Fre)", icon: "🐖", type: "Gris", dish: "Mørbrad i fad", protein: "90g Kød", sauce: "Paprika", carb: "Brasede", veg: "Ærter", biret: "Banankage (70g)" },
  { date: "2. maj (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i karry", protein: "180g Ret", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Frugtsalat (100g)" },
  { date: "3. maj (Søn)", icon: "🐂", type: "Okse", dish: "Gl.dags Oksesteg", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Bønner", biret: "Rabarbertrifli (90g)", isHoliday: true },
  { date: "4. maj (Man)", icon: "🐖", type: "Gris", dish: "Svensk Pølseret", protein: "200g Ret", sauce: "-", carb: "Kartofler", veg: "Purløg", biret: "Tomatsuppe (150g)" },
  { date: "5. maj (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Unghanebryst", protein: "90g Kød", sauce: "Skysauce", carb: "Kartofler", veg: "Agurkesalat", biret: "Chokoladekage (70g)" },
  { date: "6. maj (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred", protein: "90g Fisk", sauce: "Dild", carb: "Kartofler", veg: "Citron", biret: "Karamelrand (90g)" },
  { date: "7. maj (Tor)", icon: "🥦", type: "Grøn", dish: "Spinattærte", protein: "150g Ret", sauce: "-", carb: "-", veg: "Tomatsalat", biret: "Aspargessuppe (150g)" },
  { date: "8. maj (Fre)", icon: "🐖", type: "Gris", dish: "Mørbradgryde", protein: "180g Ret", sauce: "Paprika", carb: "Kartoffelmos", veg: "Pølser", biret: "Sandkage (70g)" },
  { date: "9. maj (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g Ret", sauce: "Asparges", carb: "Tarteletter", veg: "Tomat", biret: "Æblegrød m. fløde (150g)" },
  { date: "10. maj (Søn)", icon: "🐂", type: "Okse", dish: "Kalvesteg", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Waldorf", biret: "Budding m. saft (100g)", isHoliday: true },
  { date: "11. maj (Man)", icon: "🐖", type: "Gris", dish: "Brændende Kærlighed", protein: "Bacon", sauce: "-", carb: "Mos", veg: "Løg", biret: "Kartoffel-porresuppe (150g)" },
  { date: "12. maj (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g Ret", sauce: "Fløde", carb: "Ris", veg: "Broccoli", biret: "Mazarinkage (70g)" },
  { date: "13. maj (Ons)", icon: "🐟", type: "Fisk", dish: "Ovnbagt Ørred", protein: "90g Fisk", sauce: "Citron", carb: "Kartofler", veg: "Spinat", biret: "Jordbærgrød (150g)" },
  { date: "14. maj (Tor)", icon: "🐂", type: "Okse", dish: "Kr. HIMMEL: Engelsk Bøf", protein: "90g Kød", sauce: "Brun sauce", carb: "Kartofler", veg: "Bløde løg", biret: "Hønsekødssuppe (150g)", isHoliday: true },
  { date: "15. maj (Fre)", icon: "🐖", type: "Gris", dish: "Stegt Flæsk", protein: "90g Kød", sauce: "Persille", carb: "Kartofler", veg: "Rødbeder", biret: "Citronmåne (70g)" },
  { date: "16. maj (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Paprikagryde", protein: "180g Ret", sauce: "Paprika", carb: "Ris", veg: "Persille", biret: "Frugtgrød (150g)" },
  { date: "17. maj (Søn)", icon: "🐂", type: "Okse", dish: "Oksesteg", protein: "90g Kød", sauce: "Portvin", carb: "Flødekart.", veg: "Gulerødder", biret: "Citronfromage (90g)", isHoliday: true },
  { date: "18. maj (Man)", icon: "🐖", type: "Gris", dish: "Boller i Karry", protein: "90g Kød", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Minestronesuppe (150g)" },
  { date: "19. maj (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingedeller", protein: "2stk", sauce: "Sky", carb: "Kartofler", veg: "Rødkål", biret: "Gulerodskage (70g)" },
  { date: "20. maj (Ons)", icon: "🐟", type: "Fisk", dish: "Fiskefrikadeller", protein: "2stk", sauce: "Remoulade", carb: "Kartofler", veg: "Citron", biret: "Henkogte pærer (100g)" },
  { date: "21. maj (Tor)", icon: "🥦", type: "Grøn", dish: "Porretærte", protein: "150g Ret", sauce: "-", carb: "-", veg: "Tomatsalat", biret: "Grøntsagssuppe (150g)" },
  { date: "22. maj (Fre)", icon: "🐖", type: "Gris", dish: "Forloren Hare", protein: "90g Kød", sauce: "Vildtsauce", carb: "Kartofler", veg: "Ribsgelé", biret: "Hindbærsnitte (60g)" },
  { date: "23. maj (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Sprængt Kylling", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Gulerødder", biret: "Sveskegrød (150g)" },
  { date: "24. maj (Søn)", icon: "🐂", type: "Okse", dish: "PINSEDAG: Lammekølle", protein: "90g Kød", sauce: "Sky", carb: "Flødekart.", veg: "Bønner", biret: "Ymerfromage (90g)", isHoliday: true },
  { date: "25. maj (Man)", icon: "🐖", type: "Gris", dish: "2. PINSEDAG: Kamsteg", protein: "90g Kød", sauce: "Brun sauce", carb: "Kartofler", veg: "Rødkål", biret: "Klar suppe (150g)", isHoliday: true },
  { date: "26. maj (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Peberrod", protein: "180g Ret", sauce: "Peberrod", carb: "Kartofler", veg: "Ærter", biret: "Banankage (70g)" },
  { date: "27. maj (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g Fisk", sauce: "Persillesauce", carb: "Kartofler", veg: "Citron", biret: "Panna Cotta (90g)" },
  { date: "28. maj (Tor)", icon: "🥦", type: "Grøn", dish: "Blomkålsgratin", protein: "160g Ret", sauce: "Smør", carb: "Rugbrød", veg: "Gulerodssalat", biret: "Karrysuppe (150g)" },
  { date: "29. maj (Fre)", icon: "🐖", type: "Gris", dish: "Karbonader", protein: "1stk/110g", sauce: "Stuvede ærter", carb: "Kartofler", veg: "Gulerødder", biret: "Kage m. creme (70g)" },
  { date: "30. maj (Lør)", icon: "🐔", type: "Fjerkræ", dish: "BBQ Kylling", protein: "90g Kød", sauce: "BBQ", carb: "Kartofler", veg: "Coleslaw", biret: "Frugtsalat (100g)" },
  { date: "31. maj (Søn)", icon: "🐂", type: "Okse", dish: "Benløse Fugle", protein: "90g Kød", sauce: "Sky", carb: "Mos", veg: "Tyttebær", biret: "Chokolademousse (80g)", isHoliday: true },
];

export const june2026: MealDay[] = [
  { date: "1. jun (Man)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2 stk", sauce: "Brun sauce", carb: "Nye Kartofler", veg: "Surkål", biret: "Hyldeblomstsuppe (150g)" },
  { date: "2. jun (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i frikassé", protein: "180g Ret", sauce: "Frikassé", carb: "Kartofler", veg: "Ærter/Gulerød.", biret: "Drømmekage (70g)" },
  { date: "3. jun (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred (Vejle)", protein: "90g Fisk", sauce: "Dild", carb: "Kartofler", veg: "Citron", biret: "Jordbærgrød m. fløde (150g)" },
  { date: "4. jun (Tor)", icon: "🥦", type: "Grøn", dish: "Sommertærte", protein: "150g Ret", sauce: "-", carb: "-", veg: "Tomat", biret: "Aspargessuppe (150g)" },
  { date: "5. jun (Fre)", icon: "🐂", type: "Okse", dish: "GRUNDLOVSDAG: Engelsk Bøf", protein: "90g Kød", sauce: "Brun sauce", carb: "Kartofler", veg: "Bløde løg", biret: "Kringle (70g)", isHoliday: true },
  { date: "6. jun (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingebryst", protein: "90g Kød", sauce: "Sky", carb: "Kartofler", veg: "Rabarber", biret: "Rabarbertrifli (90g)" },
  { date: "7. jun (Søn)", icon: "🐂", type: "Okse", dish: "Kalvesteg", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Waldorf", biret: "Citronfromage (90g)", isHoliday: true },
  { date: "8. jun (Man)", icon: "🐖", type: "Gris", dish: "Skinkegryde", protein: "180g Ret", sauce: "Paprika", carb: "Ris", veg: "Pølser", biret: "Karrysuppe (150g)" },
  { date: "9. jun (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingedeller", protein: "2 stk", sauce: "Sky", carb: "Kartofler", veg: "Agurk", biret: "Chokoladekage (70g)" },
  { date: "10. jun (Ons)", icon: "🐟", type: "Fisk", dish: "Bagt Ørred (Vejle)", protein: "90g Fisk", sauce: "Persille", carb: "Kartofler", veg: "Citron", biret: "Frugtsalat m. creme (100g)" },
  { date: "11. jun (Tor)", icon: "🥦", type: "Grøn", dish: "Broccoligratin", protein: "160g Ret", sauce: "Smør", carb: "Rugbrød", veg: "Gulerod", biret: "Kartoffel-porresuppe (150g)" },
  { date: "12. jun (Fre)", icon: "🐖", type: "Gris", dish: "Koteletter i fad", protein: "110g Kød", sauce: "Tomat", carb: "Ris", veg: "-", biret: "Sandkage (70g)" },
  { date: "13. jun (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Karry", protein: "180g Ret", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Koldskål (150g)" },
  { date: "14. jun (Søn)", icon: "🐂", type: "Okse", dish: "Gl.dags Oksesteg", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Grønne bønner", biret: "Jordbær m. fløde (150g)", isHoliday: true },
  { date: "15. jun (Man)", icon: "🐖", type: "Gris", dish: "Svensk Pølseret", protein: "200g Ret", sauce: "-", carb: "Kartofler", veg: "Purløg", biret: "Tomatsuppe (150g)" },
  { date: "16. jun (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g Ret", sauce: "Fløde", carb: "Mos", veg: "Gulerødder", biret: "Mazarinkage (70g)" },
  { date: "17. jun (Ons)", icon: "🐟", type: "Fisk", dish: "Fiskefrikadeller", protein: "2 stk", sauce: "Remoulade", carb: "Kartofler", veg: "Citron", biret: "Henkogte pærer (100g)" },
  { date: "18. jun (Tor)", icon: "🥦", type: "Grøn", dish: "Vegetarisk Postej", protein: "110g Postej", sauce: "Sky", carb: "Kartofler", veg: "Agurk", biret: "Grøntsagssuppe (150g)" },
  { date: "19. jun (Fre)", icon: "🐖", type: "Gris", dish: "Stegt Flæsk", protein: "90g Kød", sauce: "Persille", carb: "Nye Kart.", veg: "Rødbeder", biret: "Citronmåne (70g)" },
  { date: "20. jun (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingelår BBQ", protein: "1 stk", sauce: "BBQ", carb: "Kartofler", veg: "Coleslaw", biret: "Sveskegrød (150g)" },
  { date: "21. jun (Søn)", icon: "🐂", type: "Okse", dish: "Sprængt Oksebryst", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Gulerødder", biret: "Budding (100g)", isHoliday: true },
  { date: "22. jun (Man)", icon: "🐖", type: "Gris", dish: "Boller i Selleri", protein: "90g Kød", sauce: "Sellerisauce", carb: "Kartofler", veg: "Persille", biret: "Klar suppe (150g)" },
  { date: "23. jun (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g Ret", sauce: "Aspargessauce", carb: "Tarteletter", veg: "Tomat", biret: "Kage m. creme (70g)" },
  { date: "24. jun (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g Fisk", sauce: "Hvidvin", carb: "Kartofler", veg: "Dild", biret: "Panna Cotta (90g)" },
  { date: "25. jun (Tor)", icon: "🥦", type: "Grøn", dish: "Ovnæggekage", protein: "150g Ret", sauce: "-", carb: "Rugbrød", veg: "Tomat", biret: "Minestronesuppe (150g)" },
  { date: "26. jun (Fre)", icon: "🐖", type: "Gris", dish: "Mørbradbøf", protein: "90g Kød", sauce: "Champignonsauce", carb: "Kartofler", veg: "Løg", biret: "Hindbærsnitte (60g)" },
  { date: "27. jun (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingeboller", protein: "90g Kød", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Rødgrød (150g)" },
  { date: "28. jun (Søn)", icon: "🐂", type: "Okse", dish: "Benløse Fugle", protein: "90g Kød", sauce: "Sky", carb: "Mos", veg: "Tyttebær", biret: "Chokolademousse (80g)", isHoliday: true },
  { date: "29. jun (Man)", icon: "🐖", type: "Gris", dish: "Brændende Kærlighed", protein: "Bacon", sauce: "-", carb: "Mos", veg: "Løg", biret: "Blomkålssuppe (150g)" },
  { date: "30. jun (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i asparges", protein: "110g Ret", sauce: "-", carb: "Tarteletter", veg: "Persille", biret: "Banankage (70g)" },
];

export const july2026: MealDay[] = [
  { date: "1. jul (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred (Vejle)", protein: "90g Fisk", sauce: "Dildsauce", carb: "Kartofler", veg: "Sommergrønt", biret: "Jordbærgrød m. fløde" },
  { date: "2. jul (Tor)", icon: "🥦", type: "Grøn", dish: "Sommergryde (Veg)", protein: "Bønner/Linser", sauce: "Tomatfløde", carb: "Ris", veg: "Squash/Peberfrugt", biret: "Koldskål (150g)" },
  { date: "3. jul (Fre)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2 stk", sauce: "Kold kartoffelsalat", carb: "(i salat)", veg: "Purløg", biret: "Drømmekage" },
  { date: "4. jul (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingebryst", protein: "90g Kød", sauce: "Skysauce", carb: "Nye Kartofler", veg: "Agurkesalat", biret: "Frugtsalat" },
  { date: "5. jul (Søn)", icon: "🐂", type: "Okse", dish: "Gl.dags Oksesteg", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Bønner", biret: "Citronfromage", isHoliday: true },
  { date: "6. jul (Man)", icon: "🐖", type: "Gris", dish: "Skinkegryde", protein: "180g Ret", sauce: "Paprika", carb: "Ris", veg: "Cocktailpølser", biret: "Tomatsuppe" },
  { date: "7. jul (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Unghanebryst", protein: "90g Kød", sauce: "Skysauce", carb: "Kartofler", veg: "Rabarberkompot", biret: "Chokoladekage" },
  { date: "8. jul (Ons)", icon: "🐟", type: "Fisk", dish: "Ovnbagt Ørred", protein: "90g Fisk", sauce: "Persillesauce", carb: "Kartofler", veg: "Citron", biret: "Rødgrød m. fløde" },
  { date: "9. jul (Tor)", icon: "🥦", type: "Grøn", dish: "Broccoligratin", protein: "160g Ret", sauce: "Smør", carb: "Rugbrød", veg: "Gulerodssalat", biret: "Aspargessuppe" },
  { date: "10. jul (Fre)", icon: "🐖", type: "Gris", dish: "Koteletter i fad", protein: "1 stk", sauce: "Tomat/Fløde", carb: "Ris", veg: "-", biret: "Sandkage" },
  { date: "11. jul (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Karry", protein: "180g Ret", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Sveskegrød" },
  { date: "12. jul (Søn)", icon: "🐂", type: "Okse", dish: "Kalvesteg", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Waldorf", biret: "Budding m. saft", isHoliday: true },
  { date: "13. jul (Man)", icon: "🐖", type: "Gris", dish: "Svensk Pølseret", protein: "200g Ret", sauce: "-", carb: "Kartofler", veg: "Purløg", biret: "Minestronesuppe" },
  { date: "14. jul (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g Ret", sauce: "Fløde", carb: "Mos", veg: "Gulerødder", biret: "Mazarinkage" },
  { date: "15. jul (Ons)", icon: "🐟", type: "Fisk", dish: "Fiskefrikadeller", protein: "2 stk", sauce: "Remoulade", carb: "Kartofler", veg: "Citron", biret: "Henkogte pærer" },
  { date: "16. jul (Tor)", icon: "🥦", type: "Grøn", dish: "Porretærte", protein: "150g Ret", sauce: "-", carb: "-", veg: "Tomatsalat", biret: "Grøntsagssuppe" },
  { date: "17. jul (Fre)", icon: "🐖", type: "Gris", dish: "Forloren Hare", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Ribsgelé", biret: "Citronmåne" },
  { date: "18. jul (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingelår BBQ", protein: "1 stk", sauce: "BBQ", carb: "Kartofler", veg: "Coleslaw", biret: "Abrikosgrød" },
  { date: "19. jul (Søn)", icon: "🐂", type: "Okse", dish: "Benløse Fugle", protein: "2 stk", sauce: "Sky", carb: "Mos", veg: "Tyttebær", biret: "Karamelrand", isHoliday: true },
  { date: "20. jul (Man)", icon: "🐖", type: "Gris", dish: "Boller i Karry", protein: "3 stk", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Klar som" },
  { date: "21. jul (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingedeller", protein: "2 stk", sauce: "Sky", carb: "Kartofler", veg: "Agurk", biret: "Banankage" },
  { date: "22. jul (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g Fisk", sauce: "Hvidvin", carb: "Kartofler", veg: "Dild", biret: "Panna Cotta" },
  { date: "23. jul (Tor)", icon: "🥦", type: "Grøn", dish: "Ovnæggekage", protein: "150g Ret", sauce: "-", carb: "Rugbrød", veg: "Tomat", biret: "Kartoffelsuppe" },
  { date: "24. jul (Fre)", icon: "🐖", type: "Gris", dish: "Stegt Flæsk", protein: "90g Kød", sauce: "Persille", carb: "Kartofler", veg: "Rødbeder", biret: "Hindbærsnitte" },
  { date: "25. jul (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Sprængt Kylling", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Gulerødder", biret: "Rabarbergrød" },
  { date: "26. jul (Søn)", icon: "🐂", type: "Okse", dish: "Hakkebøf", protein: "90g Kød", sauce: "Brun sauce", carb: "Kartofler", veg: "Bløde løg", biret: "Chokolademousse", isHoliday: true },
  { date: "27. jul (Man)", icon: "🐖", type: "Gris", dish: "Boller i Selleri", protein: "3 stk", sauce: "Selleri", carb: "Kartofler", veg: "Persille", biret: "Blomkålssuppe" },
  { date: "28. jul (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g Ret", sauce: "Asparges", carb: "Tarteletter", veg: "Tomat", biret: "Gulerodskage" },
  { date: "29. jul (Ons)", icon: "🐟", type: "Fisk", dish: "Bagt Ørred (Vejle)", protein: "90g Fisk", sauce: "Citron", carb: "Kartofler", veg: "Spinat", biret: "Frugtgrød" },
  { date: "30. jul (Tor)", icon: "🥦", type: "Grøn", dish: "Vegetarisk Postej", protein: "110g Postej", sauce: "Sky", carb: "Kartofler", veg: "Sylt. agurk", biret: "Grøntsagssuppe" },
  { date: "31. jul (Fre)", icon: "🐖", type: "Gris", dish: "Mørbradbøf", protein: "90g Kød", sauce: "Champignonsauce", carb: "Kartofler", veg: "Løg", biret: "Kage m. creme" },
];

export const august2026: MealDay[] = [
  { date: "1. aug (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i frikassé", protein: "180g Ret", sauce: "Frikassé", carb: "Kartofler", veg: "Ærter/Gulerød.", biret: "Frugtsalat m. creme (100g)" },
  { date: "2. aug (Søn)", icon: "🐂", type: "Okse", dish: "Gl.dags Oksesteg", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Grønne Bønner", biret: "Citronfromage (90g)", isHoliday: true },
  { date: "3. aug (Man)", icon: "🐖", type: "Gris", dish: "Skinkegryde", protein: "180g Ret", sauce: "Paprika", carb: "Ris", veg: "Cocktailpølser", biret: "Tomatsuppe (150g)" },
  { date: "4. aug (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Unghanebryst", protein: "90g Kød", sauce: "Sky", carb: "Kartofler", veg: "Agurkesalat", biret: "Drømmekage (70g)" },
  { date: "5. aug (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred (Vejle)", protein: "90g Fisk", sauce: "Dild", carb: "Kartofler", veg: "Citron", biret: "Rødgrød m. fløde (150g)" },
  { date: "6. aug (Tor)", icon: "🥦", type: "Grøn", dish: "Sommertærte m. spinat", protein: "150g Ret", sauce: "-", carb: "-", veg: "Tomatsalat", biret: "Aspargessuppe (150g)" },
  { date: "7. aug (Fre)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2 stk", sauce: "Kold kartoffelsalat", carb: "-", veg: "Purløg", biret: "Banankage (70g)" },
  { date: "8. aug (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingebryst", protein: "90g Kød", sauce: "Skysauce", carb: "Nye Kartofler", veg: "Rabarberkompot", biret: "Rabarbertrifli (90g)" },
  { date: "9. aug (Søn)", icon: "🐂", type: "Okse", dish: "Kalvesteg", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Waldorf", biret: "Karamelrand (90g)", isHoliday: true },
  { date: "10. aug (Man)", icon: "🐖", type: "Gris", dish: "Svensk Pølseret", protein: "200g Ret", sauce: "-", carb: "Kartofler", veg: "Purløg", biret: "Karrysuppe (150g)" },
  { date: "11. aug (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingedeller", protein: "2 stk", sauce: "Skysauce", carb: "Kartofler", veg: "Agurkesalat", biret: "Chokoladekage (70g)" },
  { date: "12. aug (Ons)", icon: "🐟", type: "Fisk", dish: "Bagt Ørred (Vejle)", protein: "90g Fisk", sauce: "Persillesauce", carb: "Kartofler", veg: "Citron", biret: "Frugtsalat m. creme (100g)" },
  { date: "13. aug (Tor)", icon: "🥦", type: "Grøn", dish: "Broccoligratin", protein: "160g Ret", sauce: "Smør", carb: "Rugbrød", veg: "Gulerodssalat", biret: "Kartoffel-porresuppe (150g)" },
  { date: "14. aug (Fre)", icon: "🐖", type: "Gris", dish: "Koteletter i fad", protein: "110g Kød", sauce: "Tomat", carb: "Ris", veg: "-", biret: "Sandkage (70g)" },
  { date: "15. aug (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Karry", protein: "180g Ret", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Koldskål m. kammerj. (150g)" },
  { date: "16. aug (Søn)", icon: "🐂", type: "Okse", dish: "Gl.dags Oksesteg", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Grønne bønner", biret: "Blommekompot m. fløde (150g)", isHoliday: true },
  { date: "17. aug (Man)", icon: "🐖", type: "Gris", dish: "Boller i Selleri", protein: "90g Kød", sauce: "Sellerisauce", carb: "Kartofler", veg: "Persille", biret: "Klar suppe m. boller (150g)" },
  { date: "18. aug (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g Ret", sauce: "Asparges", carb: "Tarteletter", veg: "Tomat", biret: "Kage m. creme (70g)" },
  { date: "19. aug (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g Fisk", sauce: "Hvidvin", carb: "Kartofler", veg: "Dild", biret: "Panna Cotta (90g)" },
  { date: "20. aug (Tor)", icon: "🥦", type: "Grøn", dish: "Ovnæggekage", protein: "150g Ret", sauce: "-", carb: "Rugbrød", veg: "Tomat/Purløg", biret: "Minestronesuppe (150g)" },
  { date: "21. aug (Fre)", icon: "🐖", type: "Gris", dish: "Mørbradbøf", protein: "90g Kød", sauce: "Champignonsauce", carb: "Kartofler", veg: "Bløde løg", biret: "Hindbærsnitte (60g)" },
  { date: "22. aug (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingeboller i karry", protein: "90g Kød", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Æblekage (90g)" },
  { date: "23. aug (Søn)", icon: "🐂", type: "Okse", dish: "Benløse Fugle", protein: "90g Kød", sauce: "Sky", carb: "Mos", veg: "Tyttebær", biret: "Chokolademousse (80g)", isHoliday: true },
  { date: "24. aug (Man)", icon: "🐖", type: "Gris", dish: "Brændende Kærlighed", protein: "Bacon", sauce: "-", carb: "Mos", veg: "Løg", biret: "Blomkålssuppe (150g)" },
  { date: "25. aug (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i asparges", protein: "110g Ret", sauce: "-", carb: "Tarteletter", veg: "Persille", biret: "Banankage (70g)" },
  { date: "26. aug (Ons)", icon: "🐟", type: "Fisk", dish: "Fiskefrikadeller", protein: "2 stk", sauce: "Remoulade", carb: "Kartofler", veg: "Citron", biret: "Henkogte pærer (100g)" },
  { date: "27. aug (Tor)", icon: "🥦", type: "Grøn", dish: "Vegetarisk Postej", protein: "110g Postej", sauce: "Sky", carb: "Kartofler", veg: "Agurk", biret: "Grøntsagssuppe (150g)" },
  { date: "28. aug (Fre)", icon: "🐖", type: "Gris", dish: "Stegt Flæsk", protein: "90g Kød", sauce: "Persille", carb: "Nye Kart.", veg: "Rødbeder", biret: "Citronmåne (70g)" },
  { date: "29. aug (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingelår BBQ", protein: "1 stk", sauce: "BBQ", carb: "Kartofler", veg: "Coleslaw", biret: "Sveskegrød (150g)" },
  { date: "30. aug (Søn)", icon: "🐂", type: "Okse", dish: "Sprængt Oksebryst", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Gulerødder", biret: "Budding m. saft (100g)", isHoliday: true },
  { date: "31. aug (Man)", icon: "🐖", type: "Gris", dish: "Krebinet", protein: "1 stk", sauce: "Stuvning", carb: "Kartofler", veg: "Persille", biret: "Klar suppe (150g)" },
];

export const september2026: MealDay[] = [
  { date: "1. sep (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Unghanebryst", protein: "90g Kød", sauce: "Skysauce", carb: "Kartofler", veg: "Agurkesalat", biret: "Kage m. creme (70g)" },
  { date: "2. sep (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred (Vejle)", protein: "90g Fisk", sauce: "Sennepsauce", carb: "Kartofler", veg: "Rødbedetern", biret: "Æblekage (90g)" },
  { date: "3. sep (Tor)", icon: "🥦", type: "Grøn", dish: "Grøntsagstærte", protein: "150g Ret", sauce: "Creme Fraiche", carb: "-", veg: "Tomatsalat", biret: "Aspargessuppe (150g)" },
  { date: "4. sep (Fre)", icon: "🐖", type: "Gris", dish: "Mørbradgryde", protein: "180g Ret", sauce: "Paprika", carb: "Ris", veg: "Pølser", biret: "Drømmekage (70g)" },
  { date: "5. sep (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g Ret", sauce: "Asparges", carb: "Tarteletter", veg: "Persille", biret: "Sveskemos (100g)" },
  { date: "6. sep (Søn)", icon: "🐂", type: "Okse", dish: "Gl.dags Oksesteg", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Bønner", biret: "Citronfromage (90g)", isHoliday: true },
  { date: "7. sep (Man)", icon: "🐖", type: "Gris", dish: "Brændende Kærlighed", protein: "Bacon", sauce: "-", carb: "Mos", veg: "Løg", biret: "Tomatsuppe (150g)" },
  { date: "8. sep (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Karry", protein: "180g Ret", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Gulerodskage (70g)" },
  { date: "9. sep (Ons)", icon: "🐟", type: "Fisk", dish: "Ovnbagt Ørred", protein: "90g Fisk", sauce: "Citron", carb: "Kartofler", veg: "Spinat", biret: "Pæretærte (90g)" },
  { date: "10. sep (Tor)", icon: "🥦", type: "Grøn", dish: "Kartoffel-porresuppe", protein: "-", sauce: "-", carb: "Brød", veg: "Baconknas", biret: "Pandekager (2 stk)" },
  { date: "11. sep (Fre)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2 stk", sauce: "Brun sauce", carb: "Kartofler", veg: "Surkål", biret: "Mazarinkage (70g)" },
  { date: "12. sep (Lør)", icon: "🐂", type: "Okse", dish: "Hakkebøf", protein: "90g Kød", sauce: "Bløde løg", carb: "Kartofler", veg: "Brun sauce", biret: "Frugtsalat (100g)" },
  { date: "13. sep (Søn)", icon: "🐖", type: "Gris", dish: "Ribbensteg", protein: "90g Kød", sauce: "Brun sauce", carb: "Kartofler", veg: "Rødkål", biret: "Romfromage (90g)", isHoliday: true },
  { date: "14. sep (Man)", icon: "🐖", type: "Gris", dish: "Svensk Pølseret", protein: "200g Ret", sauce: "-", carb: "Kartofler", veg: "Purløg", biret: "Minestronesuppe (150g)" },
  { date: "15. sep (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g Ret", sauce: "Fløde", carb: "Ris", veg: "Broccoli", biret: "Citronmåne (70g)" },
  { date: "16. sep (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g Fisk", sauce: "Persille", carb: "Kartofler", veg: "Citron", biret: "Henkogte pærer (100g)" },
  { date: "17. sep (Tor)", icon: "🥦", type: "Grøn", dish: "Vegetarisk Postej", protein: "110g Postej", sauce: "Sky", carb: "Kartofler", veg: "Agurk", biret: "Karrysuppe (150g)" },
  { date: "18. sep (Fre)", icon: "🐖", type: "Gris", dish: "Stegt Flæsk", protein: "90g Kød", sauce: "Persille", carb: "Kartofler", veg: "Rødbeder", biret: "Sandkage (70g)" },
  { date: "19. sep (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Paprikagryde", protein: "180g Ret", sauce: "Paprika", carb: "Ris", veg: "Persille", biret: "Jordbærgrød (150g)" },
  { date: "20. sep (Søn)", icon: "🐂", type: "Okse", dish: "Kalvesteg", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Waldorf", biret: "Sherryfromage (90g)", isHoliday: true },
  { date: "21. sep (Man)", icon: "🐖", type: "Gris", dish: "Boller i Selleri", protein: "3 stk", sauce: "Selleri", carb: "Kartofler", veg: "Persille", biret: "Blomkålssuppe (150g)" },
  { date: "22. sep (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Sprængt Kylling", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Gulerødder", biret: "Kage m. creme (70g)" },
  { date: "23. sep (Ons)", icon: "🐟", type: "Fisk", dish: "Fiskefrikadeller", protein: "2 stk", sauce: "Remoulade", carb: "Kartofler", veg: "Citron", biret: "Panna Cotta (90g)" },
  { date: "24. sep (Tor)", icon: "🥦", type: "Grøn", dish: "Ovnæggekage", protein: "150g Ret", sauce: "-", carb: "Rugbrød", veg: "Tomat", biret: "Grøntsagssuppe (150g)" },
  { date: "25. sep (Fre)", icon: "🐖", type: "Gris", dish: "Forloren Hare", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Ribsgelé", biret: "Hindbærsnitte (60g)" },
  { date: "26. sep (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Andebryst", protein: "90g And", sauce: "Sky", carb: "Kartofler", veg: "Svesker", biret: "Sveskegrød (150g)" },
  { date: "27. sep (Søn)", icon: "🐂", type: "Okse", dish: "Oksesteg", protein: "90g Kød", sauce: "Rødvin", carb: "Flødekart.", veg: "Gulerødder", biret: "Chokolademousse (80g)", isHoliday: true },
  { date: "28. sep (Man)", icon: "🐖", type: "Gris", dish: "Frikassé", protein: "180g Ret", sauce: "Frikassé", carb: "Kartofler", veg: "Urter", biret: "Blomkålssuppe (150g)" },
  { date: "29. sep (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Peberrod", protein: "180g Ret", sauce: "Peberrod", carb: "Kartofler", veg: "Ærter", biret: "Banankage (70g)" },
  { date: "30. sep (Ons)", icon: "🐟", type: "Fisk", dish: "Bagt Ørred (Vejle)", protein: "90g Fisk", sauce: "Hvidvin", carb: "Kartofler", veg: "Dild", biret: "Rabarbertrifli (90g)" },
];

export const october2026: MealDay[] = [
  { date: "1. okt (Tor)", icon: "🥦", type: "Grøn", dish: "Ovnæggekage", protein: "150g Ret", sauce: "-", carb: "Rugbrød", veg: "Tomat", biret: "Grøntsagssuppe (150g)" },
  { date: "2. okt (Fre)", icon: "🐖", type: "Gris", dish: "Mørbradbøf", protein: "90g Kød", sauce: "Champignon", carb: "Kartofler", veg: "Løg", biret: "Brunsviger (70g)" },
  { date: "3. okt (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingelår BBQ", protein: "1 stk", sauce: "BBQ", carb: "Kartofler", veg: "Coleslaw", biret: "Sveskegrød (150g)" },
  { date: "4. okt (Søn)", icon: "🐂", type: "Okse", dish: "Sprængt Oksebryst", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Gulerødder", biret: "Budding m. saft (100g)", isHoliday: true },
  { date: "5. okt (Man)", icon: "🐖", type: "Gris", dish: "Brændende Kærlighed", protein: "Bacon", sauce: "-", carb: "Mos", veg: "Løg", biret: "Kartoffelsuppe (150g)" },
  { date: "6. okt (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingedeller", protein: "2 stk", sauce: "Sky", carb: "Kartofler", veg: "Agurkesalat", biret: "Chokoladekage (70g)" },
  { date: "7. okt (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g Fisk", sauce: "Persille", carb: "Kartofler", veg: "Citron", biret: "Panna Cotta (90g)" },
  { date: "8. okt (Tor)", icon: "🥦", type: "Grøn", dish: "Vegetarisk Postej", protein: "110g Postej", sauce: "Sky", carb: "Kartofler", veg: "Agurk", biret: "Minestronesuppe (150g)" },
  { date: "9. okt (Fre)", icon: "🐖", type: "Gris", dish: "Forloren Hare", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Ribsgelé", biret: "Sandkage (70g)" },
  { date: "10. okt (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g Ret", sauce: "Asparges", carb: "Tarteletter", veg: "Tomat", biret: "Æblekage (90g)" },
  { date: "11. okt (Søn)", icon: "🐂", type: "Okse", dish: "Hakkebøf", protein: "90g Kød", sauce: "Brun sauce", carb: "Kartofler", veg: "Bløde løg", biret: "Citronfromage (90g)", isHoliday: true },
  { date: "12. okt (Man)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2 stk", sauce: "Brun sauce", carb: "Kartofler", veg: "Surkål", biret: "Aspargessuppe (150g)" },
  { date: "13. okt (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Unghanebryst", protein: "90g Kød", sauce: "Sky", carb: "Kartofler", veg: "Agurk", biret: "Mazarinkage (70g)" },
  { date: "14. okt (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred", protein: "90g Fisk", sauce: "Urtecreme", carb: "Kartofler", veg: "Dild", biret: "Frugtsalat (100g)" },
  { date: "15. okt (Tor)", icon: "🥦", type: "Grøn", dish: "Porretærte", protein: "150g Ret", sauce: "-", carb: "-", veg: "Tomatsalat", biret: "Karrysuppe (150g)" },
  { date: "16. okt (Fre)", icon: "🐖", type: "Gris", dish: "Skinke m. flødekart.", protein: "90g Skinke", sauce: "-", carb: "Flødekart.", veg: "Bønner", biret: "Citronmåne (70g)" },
  { date: "17. okt (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingeboller", protein: "90g Kød", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Sveskegrød (150g)" },
  { date: "18. okt (Søn)", icon: "🐂", type: "Okse", dish: "Sprængt Oksebryst", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Gulerødder", biret: "Budding (100g)", isHoliday: true },
  { date: "19. okt (Man)", icon: "🐖", type: "Gris", dish: "Svensk Pølseret", protein: "200g Ret", sauce: "-", carb: "Kartofler", veg: "Purløg", biret: "Klar suppe (150g)" },
  { date: "20. okt (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Sprængt Kylling", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Gulerødder", biret: "Banankage (70g)" },
  { date: "21. okt (Ons)", icon: "🐟", type: "Fisk", dish: "Ovnbagt Ørred", protein: "90g Fisk", sauce: "Citron", carb: "Kartofler", veg: "Spinat", biret: "Henkogte pærer (100g)" },
  { date: "22. okt (Tor)", icon: "🥦", type: "Grøn", dish: "Grøntsagslasagne", protein: "200g Ret", sauce: "-", carb: "Brød", veg: "Råkost", biret: "Grøntsagssuppe (150g)" },
  { date: "23. okt (Fre)", icon: "🐖", type: "Gris", dish: "Karbonader", protein: "1 stk", sauce: "Stuvede ærter", carb: "Kartofler", veg: "Gulerødder", biret: "Hindbærsnitte (60g)" },
  { date: "24. okt (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Paprikagryde", protein: "180g Ret", sauce: "Paprika", carb: "Ris", veg: "Persille", biret: "Frugtsalat (100g)" },
  { date: "25. okt (Søn)", icon: "🐂", type: "Okse", dish: "Gl.dags Oksesteg", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Bønner", biret: "Chokolademousse (80g)", isHoliday: true },
  { date: "26. okt (Man)", icon: "🐖", type: "Gris", dish: "Boller i Karry", protein: "3 stk", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Blomkålssuppe (150g)" },
  { date: "27. okt (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g Ret", sauce: "Fløde", carb: "Mos", veg: "Broccoli", biret: "Kage m. creme (70g)" },
  { date: "28. okt (Ons)", icon: "🐟", type: "Fisk", dish: "Fiskefrikadeller", protein: "2 stk", sauce: "Remoulade", carb: "Kartofler", veg: "Citron", biret: "Rødgrød (150g)" },
  { date: "29. okt (Tor)", icon: "🥦", type: "Grøn", dish: "Blomkålsgratin", protein: "160g Ret", sauce: "Smør", carb: "Rugbrød", veg: "Gulerod", biret: "Hønsekødssuppe (150g)" },
  { date: "30. okt (Fre)", icon: "🐖", type: "Gris", dish: "Krebinet", protein: "1 stk", sauce: "Stuvning", carb: "Kartofler", veg: "Persille", biret: "Brunsviger (70g)" },
  { date: "31. okt (Lør) 🎃", icon: "🥦", type: "Grøn", dish: "HALLOWEEN: Græskarsuppe", protein: "Baconknas", sauce: "-", carb: "Brød", veg: "Græskar", biret: "Jordbærgrød (150g)", isHoliday: true },
];

export const november2026: MealDay[] = [
  { date: "1. nov (Søn)", icon: "🐂", type: "Okse", dish: "Benløse Fugle", protein: "2 stk", sauce: "Sky", carb: "Mos", veg: "Tyttebær", biret: "Sherryfromage", isHoliday: true },
  { date: "2. nov (Man)", icon: "🐖", type: "Gris", dish: "Svensk Pølseret", protein: "200g Ret", sauce: "-", carb: "Kartofler", veg: "Purløg", biret: "Tomatsuppe" },
  { date: "3. nov (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Karry", protein: "180g Ret", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Drømmekage" },
  { date: "4. nov (Ons)", icon: "🐟", type: "Fisk", dish: "Bagt Ørred (Vejle)", protein: "90g Fisk", sauce: "Persille", carb: "Kartofler", veg: "Citron", biret: "Panna Cotta" },
  { date: "5. nov (Tor)", icon: "🥦", type: "Grøn", dish: "Gule Ærter", protein: "Flæsk", sauce: "-", carb: "-", veg: "Sennep", biret: "Pandekager" },
  { date: "6. nov (Fre)", icon: "🐖", type: "Gris", dish: "Mørbradgryde", protein: "180g Ret", sauce: "Paprika", carb: "Ris", veg: "Pølser", biret: "Sandkage" },
  { date: "7. nov (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g Ret", sauce: "Aspargessauce", carb: "Tarteletter", veg: "Tomat", biret: "Æblegrød" },
  { date: "8. nov (Søn)", icon: "🐂", type: "Okse", dish: "Kalvesteg", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Waldorf", biret: "Karamelrand", isHoliday: true },
  { date: "9. nov (Man)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2 stk", sauce: "Brun sauce", carb: "Kartofler", veg: "Surkål", biret: "Karrysuppe" },
  { date: "10. nov (Tir) 🦆", icon: "🦆", type: "Fjerkræ", dish: "Andesteg", protein: "90g And", sauce: "Andesauce", carb: "Hvide/Brunede", veg: "Rødkål", biret: "Gammeldags Æblekage", isHoliday: true },
  { date: "11. nov (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g Fisk", sauce: "Hvidvin", carb: "Kartofler", veg: "Dild", biret: "Rabarbertrifli" },
  { date: "12. nov (Tor)", icon: "🥦", type: "Grøn", dish: "Ovnæggekage", protein: "150g Ret", sauce: "-", carb: "Rugbrød", veg: "Tomat", biret: "Kartoffel-porresuppe" },
  { date: "13. nov (Fre)", icon: "🐖", type: "Gris", dish: "Stegt Flæsk", protein: "90g Kød", sauce: "Persille", carb: "Kartofler", veg: "Rødbeder", biret: "Chokoladekage" },
  { date: "14. nov (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingefrikassé", protein: "180g Ret", sauce: "Frikassé", carb: "Kartofler", veg: "Grønt", biret: "Sveskegrød" },
  { date: "15. nov (Søn)", icon: "🐂", type: "Okse", dish: "Oksesteg", protein: "90g Kød", sauce: "Portvin", carb: "Flødekart.", veg: "Bønner", biret: "Citronfromage", isHoliday: true },
  { date: "16. nov (Man)", icon: "🐖", type: "Gris", dish: "Boller i Selleri", protein: "3 stk", sauce: "Sellerisauce", carb: "Kartofler", veg: "Persille", biret: "Aspargessuppe" },
  { date: "17. nov (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Unghanebryst", protein: "90g Kød", sauce: "Sky", carb: "Kartofler", veg: "Agurk", biret: "Citronmåne" },
  { date: "18. nov (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred", protein: "90g Fisk", sauce: "Citron", carb: "Kartofler", veg: "Spinat", biret: "Budding" },
  { date: "19. nov (Tor)", icon: "🥦", type: "Grøn", dish: "Spinattærte", protein: "150g Ret", sauce: "-", carb: "-", veg: "Tomatsalat", biret: "Minestronesuppe" },
  { date: "20. nov (Fre)", icon: "🐖", type: "Gris", dish: "Forloren Hare", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Tyttebær", biret: "Mazarinkage" },
  { date: "21. nov (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Paprikagryde", protein: "180g Ret", sauce: "Paprika", carb: "Ris", veg: "Persille", biret: "Frugtsalat" },
  { date: "22. nov (Søn)", icon: "🐂", type: "Okse", dish: "Hakkebøf", protein: "90g Kød", sauce: "Brun sauce", carb: "Kartofler", veg: "Bløde løg", biret: "Ymerfromage", isHoliday: true },
  { date: "23. nov (Man)", icon: "🐖", type: "Gris", dish: "Skipperlabskovs", protein: "250g Ret", sauce: "-", carb: "Rugbrød", veg: "Rødbeder", biret: "Klar suppe" },
  { date: "24. nov (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Sprængt Kylling", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Gulerødder", biret: "Banankage" },
  { date: "25. nov (Ons)", icon: "🐟", type: "Fisk", dish: "Fiskefrikadeller", protein: "2 stk", sauce: "Remoulade", carb: "Kartofler", veg: "Citron", biret: "Henkogte pærer" },
  { date: "26. nov (Tor)", icon: "🥦", type: "Grøn", dish: "Porretærte", protein: "150g Ret", sauce: "-", carb: "-", veg: "Tomatsalat", biret: "Grøntsagssuppe" },
  { date: "27. nov (Fre)", icon: "🐖", type: "Gris", dish: "Karbonader", protein: "1 stk", sauce: "Stuvede ærter", carb: "Kartofler", veg: "Gulerød", biret: "Hindbærsnitte" },
  { date: "28. nov (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g Ret", sauce: "Fløde", carb: "Ris", veg: "Broccoli", biret: "Frugtgrød" },
  { date: "29. nov (Søn) 🕯️", icon: "🐖", type: "Gris", dish: "Julemedister", protein: "110g Pølse", sauce: "Brun sauce", carb: "Kartofler", veg: "Rødkål", biret: "Risengrød", isHoliday: true },
  { date: "30. nov (Man)", icon: "🐖", type: "Gris", dish: "Mørbrad i fad", protein: "90g Kød", sauce: "Paprika", carb: "Brasede", veg: "Ærter", biret: "Kartoffelsuppe" },
];

export const december2026: MealDay[] = [
  { date: "1. dec (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Karry", protein: "180g Ret", sauce: "Karry", carb: "Ris", veg: "Mango", biret: "Kage m. creme" },
  { date: "2. dec (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g Fisk", sauce: "Persille", carb: "Kartofler", veg: "Citron", biret: "Jordbærgrød" },
  { date: "3. dec (Tor)", icon: "🥦", type: "Grøn", dish: "Blomkålsgratin", protein: "160g Ret", sauce: "Smør", carb: "Rugbrød", veg: "Gulerod", biret: "Tomatsuppe" },
  { date: "4. dec (Fre)", icon: "🐖", type: "Gris", dish: "Mørbradbøf", protein: "90g Kød", sauce: "Champignon", carb: "Kartofler", veg: "Løg", biret: "Brunsviger" },
  { date: "5. dec (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingeboller", protein: "90g Kød", sauce: "Karry", carb: "Ris", veg: "Chutney", biret: "Risengrød" },
  { date: "6. dec (Søn) 🕯️🕯️", icon: "🐂", type: "Okse", dish: "Benløse Fugle", protein: "2 stk", sauce: "Sky", carb: "Mos", veg: "Tyttebær", biret: "Citronfromage", isHoliday: true },
  { date: "7. dec (Man)", icon: "🐖", type: "Gris", dish: "Brændende Kærlighed", protein: "Bacon", sauce: "-", carb: "Mos", veg: "Løg", biret: "Karrysuppe" },
  { date: "8. dec (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i asparges", protein: "110g Ret", sauce: "-", carb: "Tarteletter", veg: "Persille", biret: "Gulerodskage" },
  { date: "9. dec (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred", protein: "90g Fisk", sauce: "Dild", carb: "Kartofler", veg: "Citron", biret: "Pæretærte" },
  { date: "10. dec (Tor)", icon: "🥦", type: "Grøn", dish: "Grøntsagslasagne", protein: "200g Ret", sauce: "-", carb: "Brød", veg: "Råkost", biret: "Aspargessuppe" },
  { date: "11. dec (Fre)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2 stk", sauce: "Brun sauce", carb: "Kartofler", veg: "Rødkål", biret: "Drømmekage" },
  { date: "12. dec (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Andebryst", protein: "90g And", sauce: "Sky", carb: "Kartofler", veg: "Svesker", biret: "Frugtsalat" },
  { date: "13. dec (Søn) 🕯️🕯️🕯️", icon: "🐂", type: "Okse", dish: "Kalvesteg", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Waldorf", biret: "Rubinsteinerkage", isHoliday: true },
  { date: "14. dec (Man)", icon: "🐖", type: "Gris", dish: "Koteletter i fad", protein: "1 stk", sauce: "Tomat/Fløde", carb: "Ris", veg: "-", biret: "Kartoffel-porresuppe" },
  { date: "15. dec (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Unghanebryst", protein: "90g Kød", sauce: "Sky", carb: "Kartofler", veg: "Agurk", biret: "Chokoladekage" },
  { date: "16. dec (Ons)", icon: "🐟", type: "Fisk", dish: "Bagt Ørred (Vejle)", protein: "90g Fisk", sauce: "Mandel", carb: "Kartofler", veg: "Grønt", biret: "Rabarbertrifli" },
  { date: "17. dec (Tor)", icon: "🥦", type: "Grøn", dish: "Spinattærte", protein: "150g Ret", sauce: "-", carb: "-", veg: "Tomat", biret: "Klar suppe" },
  { date: "18. dec (Fre)", icon: "🐖", type: "Gris", dish: "Ribbensteg", protein: "90g Kød", sauce: "Brun sauce", carb: "Kartofler", veg: "Rødkål", biret: "Æblekage" },
  { date: "19. dec (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g Ret", sauce: "Fløde", carb: "Mos", veg: "Gulerødder", biret: "Sveskegrød" },
  { date: "20. dec (Søn) 🕯️🕯️🕯️🕯️", icon: "🐂", type: "Okse", dish: "Wienerschnitzel", protein: "110g Kalv", sauce: "Smør", carb: "Brasede", veg: "Ærter", biret: "Appelsinfromage", isHoliday: true },
  { date: "21. dec (Man)", icon: "🐖", type: "Gris", dish: "Svensk Pølseret", protein: "200g Ret", sauce: "-", carb: "Kartofler", veg: "Purløg", biret: "Minestronesuppe" },
  { date: "22. dec (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingelår BBQ", protein: "1 stk", sauce: "BBQ", carb: "Kartofler", veg: "Coleslaw", biret: "Citronmåne" },
  { date: "23. dec (Ons)", icon: "🐟", type: "Fisk", dish: "Lillejuleaften: Stegt Sild", protein: "110g Sild", sauce: "Løg", carb: "Rugbrød", veg: "Karrysalat", biret: "Risengrød" },
  { date: "24. dec (Tor) 🎄", icon: "🐖", type: "Gris", dish: "JULEAFTEN: And/Flæskesteg", protein: "120g Kød", sauce: "Julesauce", carb: "Hvide/Brunede", veg: "Rødkål", biret: "Risalamande m. kirsebær", isHoliday: true },
  { date: "25. dec (Fre) 🎅", icon: "🐂", type: "Okse", dish: "JULEDAG: Kalvesteg", protein: "90g Kød", sauce: "Vildt", carb: "Kartofler", veg: "Waldorf", biret: "Frugtsalat", isHoliday: true },
  { date: "26. dec (Lør) 🎁", icon: "🐖", type: "Gris", dish: "2. JULEDAG: Julefrikadeller", protein: "2 stk", sauce: "Brun sauce", carb: "Kartofler", veg: "Surkål", biret: "Chokoladekage", isHoliday: true },
  { date: "27. dec (Søn)", icon: "🐂", type: "Okse", dish: "Gl.dags Oksesteg", protein: "90g Kød", sauce: "Peberrod", carb: "Kartofler", veg: "Bønner", biret: "Rabarbertrifli", isHoliday: true },
  { date: "28. dec (Man)", icon: "🐖", type: "Gris", dish: "Skipperlabskovs", protein: "250g Ret", sauce: "-", carb: "Rugbrød", veg: "Rødbeder", biret: "Aspargessuppe" },
  { date: "29. dec (Tir)", icon: "🐂", type: "Okse", dish: "Hakkebøf", protein: "90g Kød", sauce: "Bearnaise", carb: "Kartofler", veg: "Bløde løg", biret: "Citronfromage" },
  { date: "30. dec (Ons)", icon: "🐟", type: "Fisk", dish: "Torskefad", protein: "90g Fisk", sauce: "Sennep", carb: "Kartofler", veg: "Æg/Rejer", biret: "Frugtgrød" },
  { date: "31. dec (Tor) 🎆", icon: "🐂", type: "Okse", dish: "NYTÅRSAFTEN: Oksemørbrad", protein: "120g Kød", sauce: "Rødvin", carb: "Flødekart.", veg: "Bønner", biret: "Nytårskage", isHoliday: true },
];

export const yearlyPlan2026: Record<string, { label: string, title: string, data: MealDay[] }> = {
  january: { label: 'Januar', title: 'Januarmenuplan', data: january2026 },
  february: { label: 'Februar', title: 'Februarmenuplan', data: february2026 },
  march: { label: 'Marts', title: 'Martsmenuplan', data: march2026 },
  april: { label: 'April', title: 'Aprilmenuplan', data: april2026 },
  may: { label: 'Maj', title: 'Majmenuplan', data: may2026 },
  june: { label: 'Juni', title: 'Junimenuplan', data: june2026 },
  july: { label: 'Juli', title: 'Julimenuplan', data: july2026 },
  august: { label: 'August', title: 'Augustmenuplan', data: august2026 },
  september: { label: 'September', title: 'Septembermenuplan', data: september2026 },
  october: { label: 'Oktober', title: 'Oktobermenuplan', data: october2026 },
  november: { label: 'November', title: 'Novembermenuplan', data: november2026 },
  december: { label: 'December', title: 'Decembermenuplan', data: december2026 },
};
