// CaterCare Complete Recipe Database - Sprint 3-5
// Desserter, Supper, Tilbehør og Kulhydrater
// Genereret: 2026-01-12

// ===== SPRINT 3: ALLE DESSERTER & KAGER =====
export const desserterKomplet: Record<string, any> = {
    // FROMAGER
    "DS-011": { recipeName: "Karamelrand", id: "DS-011", category: "Desserter", yield_net: "15.0 KG", ingredients: [{ name: "Mælk", quantity: 6000, unit: "ml" }, { name: "Æg", quantity: 1500, unit: "g" }, { name: "Sukker (karamel)", quantity: 1500, unit: "g" }, { name: "Sukker (creme)", quantity: 800, unit: "g" }, { name: "Vanilje", quantity: 20, unit: "g" }], method: ["Lav karamel, hæld i form.", "Pisk æg og sukker.", "Tilsæt varm mælk.", "Hæld i form, bag i vandbad.", "Køl og vend ud."] },
    "DS-012": { recipeName: "Romfromage", id: "DS-012", category: "Desserter", yield_net: "12.0 KG", ingredients: [{ name: "Æggeblommer", quantity: 800, unit: "g" }, { name: "Sukker", quantity: 600, unit: "g" }, { name: "Husblas", quantity: 80, unit: "g" }, { name: "Rom", quantity: 400, unit: "ml" }, { name: "Piskefløde", quantity: 4000, unit: "ml" }], method: ["Pisk blommer og sukker.", "Smelt husblas i rom.", "Bland i blommemasse.", "Vend pisket fløde i.", "Køl til stivnet."] },
    "DS-013": { recipeName: "Sherryfromage", id: "DS-013", category: "Desserter", yield_net: "12.0 KG", ingredients: [{ name: "Æggeblommer", quantity: 800, unit: "g" }, { name: "Sukker", quantity: 600, unit: "g" }, { name: "Husblas", quantity: 80, unit: "g" }, { name: "Sherry", quantity: 400, unit: "ml" }, { name: "Piskefløde", quantity: 4000, unit: "ml" }], method: ["Pisk blommer og sukker.", "Smelt husblas i sherry.", "Bland og vend fløde i.", "Køl."] },
    "DS-014": { recipeName: "Ymerfromage", id: "DS-014", category: "Desserter", yield_net: "10.0 KG", ingredients: [{ name: "Ymer", quantity: 5000, unit: "g" }, { name: "Sukker", quantity: 800, unit: "g" }, { name: "Husblas", quantity: 60, unit: "g" }, { name: "Citronsaft", quantity: 200, unit: "ml" }, { name: "Piskefløde", quantity: 3000, unit: "ml" }], method: ["Rør ymer med sukker og citron.", "Smelt husblas, rør i.", "Vend pisket fløde i.", "Køl."] },
    "DS-015": { recipeName: "Appelsinfromage", id: "DS-015", category: "Desserter", yield_net: "12.0 KG", ingredients: [{ name: "Appelsinsaft", quantity: 2000, unit: "ml" }, { name: "Appelsinskaller", quantity: 100, unit: "g" }, { name: "Sukker", quantity: 800, unit: "g" }, { name: "Husblas", quantity: 80, unit: "g" }, { name: "Piskefløde", quantity: 4000, unit: "ml" }], method: ["Varm saft med sukker.", "Smelt husblas i.", "Køl til tykkelse.", "Vend fløde i."] },
    // GRØD OG KOMPOT
    "DS-016": { recipeName: "Rødgrød m. fløde", id: "DS-016", category: "Desserter", yield_net: "20.0 KG", ingredients: [{ name: "Bær (blanding)", quantity: 10000, unit: "g" }, { name: "Sukker", quantity: 2000, unit: "g" }, { name: "Kartoffelmel", quantity: 400, unit: "g" }, { name: "Vand", quantity: 5000, unit: "ml" }], method: ["Kog bær i vand.", "Tilsæt sukker.", "Jævn med kartoffelmel.", "Køl.", "Server med fløde."] },
    "DS-017": { recipeName: "Jordbærgrød", id: "DS-017", category: "Desserter", yield_net: "18.0 KG", ingredients: [{ name: "Jordbær", quantity: 10000, unit: "g" }, { name: "Sukker", quantity: 2000, unit: "g" }, { name: "Kartoffelmel", quantity: 300, unit: "g" }], method: ["Kog jordbær let.", "Tilsæt sukker.", "Jævn.", "Køl."] },
    "DS-018": { recipeName: "Æblegrød", id: "DS-018", category: "Desserter", yield_net: "20.0 KG", ingredients: [{ name: "Æbler", quantity: 15000, unit: "g" }, { name: "Sukker", quantity: 2000, unit: "g" }, { name: "Vand", quantity: 3000, unit: "ml" }, { name: "Vanilje", quantity: 20, unit: "g" }], method: ["Kog æbler møre.", "Mos eller blend.", "Tilsæt sukker og vanilje."] },
    "DS-019": { recipeName: "Rabarbergrød", id: "DS-019", category: "Desserter", yield_net: "18.0 KG", ingredients: [{ name: "Rabarber", quantity: 12000, unit: "g" }, { name: "Sukker", quantity: 3000, unit: "g" }, { name: "Kartoffelmel", quantity: 300, unit: "g" }], method: ["Kog rabarber.", "Tilsæt sukker.", "Jævn.", "Køl."] },
    "DS-020": { recipeName: "Abrikosgrød", id: "DS-020", category: "Desserter", yield_net: "15.0 KG", ingredients: [{ name: "Abrikoser, tørrede", quantity: 5000, unit: "g" }, { name: "Vand", quantity: 8000, unit: "ml" }, { name: "Sukker", quantity: 1500, unit: "g" }, { name: "Kartoffelmel", quantity: 250, unit: "g" }], method: ["Læg abrikoser i blød.", "Kog møre.", "Jævn.", "Køl."] },
    "DS-021": { recipeName: "Henkogte pærer", id: "DS-021", category: "Desserter", yield_net: "15.0 KG", ingredients: [{ name: "Pærer", quantity: 12000, unit: "g" }, { name: "Sukker", quantity: 2000, unit: "g" }, { name: "Vand", quantity: 3000, unit: "ml" }, { name: "Vanilje", quantity: 10, unit: "g" }], method: ["Skræl pærer.", "Kog i sukkersirup.", "Lad trække.", "Server kolde."] },
    "DS-022": { recipeName: "Frugtgrød", id: "DS-022", category: "Desserter", yield_net: "18.0 KG", ingredients: [{ name: "Blandet frugt", quantity: 10000, unit: "g" }, { name: "Sukker", quantity: 2000, unit: "g" }, { name: "Kartoffelmel", quantity: 350, unit: "g" }], method: ["Kog frugt.", "Tilsæt sukker.", "Jævn.", "Køl."] },
    // KAGER
    "DS-023": { recipeName: "Citronmåne", id: "DS-023", category: "Kager", yield_net: "60 STK", ingredients: [{ name: "Smør", quantity: 800, unit: "g" }, { name: "Sukker", quantity: 800, unit: "g" }, { name: "Æg", quantity: 600, unit: "g" }, { name: "Mel", quantity: 1000, unit: "g" }, { name: "Bagepulver", quantity: 25, unit: "g" }, { name: "Citronsaft og skal", quantity: 200, unit: "g" }], method: ["Pisk smør og sukker.", "Tilsæt æg.", "Vend mel i.", "Bag i måneform.", "Glasér med citronglasur."] },
    "DS-024": { recipeName: "Gulerodskage", id: "DS-024", category: "Kager", yield_net: "60 STK", ingredients: [{ name: "Gulerødder, revet", quantity: 1500, unit: "g" }, { name: "Sukker", quantity: 1000, unit: "g" }, { name: "Olie", quantity: 800, unit: "ml" }, { name: "Æg", quantity: 600, unit: "g" }, { name: "Mel", quantity: 1000, unit: "g" }, { name: "Valnødder", quantity: 300, unit: "g" }], method: ["Bland sukker, olie og æg.", "Tilsæt gulerødder.", "Vend mel i.", "Bag ved 175°C.", "Top med cream cheese glasur."] },
    "DS-025": { recipeName: "Drømmekage", id: "DS-025", category: "Kager", yield_net: "60 STK", ingredients: [{ name: "Smør", quantity: 400, unit: "g" }, { name: "Sukker", quantity: 600, unit: "g" }, { name: "Æg", quantity: 500, unit: "g" }, { name: "Mel", quantity: 700, unit: "g" }, { name: "Kokos", quantity: 400, unit: "g" }, { name: "Brun sukker (topping)", quantity: 500, unit: "g" }], method: ["Lav grunddej.", "Bag halvt.", "Læg kokostopping på.", "Færdigbag til gylden."] },
    "DS-026": { recipeName: "Brunsviger", id: "DS-026", category: "Kager", yield_net: "60 STK", ingredients: [{ name: "Gærdej", quantity: 3000, unit: "g" }, { name: "Smør", quantity: 1000, unit: "g" }, { name: "Brun sukker", quantity: 1500, unit: "g" }, { name: "Sirup", quantity: 300, unit: "g" }], method: ["Rul dej ud.", "Lav remonce af smør/sukker.", "Fordel på dej.", "Bag ved 200°C."] },
    "DS-027": { recipeName: "Mazarinkage", id: "DS-027", category: "Kager", yield_net: "60 STK", ingredients: [{ name: "Mørdej", quantity: 2000, unit: "g" }, { name: "Marcipan", quantity: 2000, unit: "g" }, { name: "Sukker", quantity: 800, unit: "g" }, { name: "Æg", quantity: 600, unit: "g" }, { name: "Smør", quantity: 600, unit: "g" }], method: ["Beklæd forme med dej.", "Lav mazarinfyld.", "Fyld i bunde.", "Bag ved 175°C."] },
    "DS-028": { recipeName: "Hindbærsnitte", id: "DS-028", category: "Kager", yield_net: "80 STK", ingredients: [{ name: "Mørdej", quantity: 2500, unit: "g" }, { name: "Hindbærmarmelade", quantity: 2000, unit: "g" }, { name: "Romglasur", quantity: 1500, unit: "g" }], method: ["Bag dejbunde.", "Smør marmelade på.", "Sæt sammen.", "Glasér."] },
    "DS-029": { recipeName: "Æblekage", id: "DS-029", category: "Desserter", yield_net: "15.0 KG", ingredients: [{ name: "Æblemos", quantity: 8000, unit: "g" }, { name: "Tvebakker, ristede", quantity: 2000, unit: "g" }, { name: "Smør", quantity: 500, unit: "g" }, { name: "Sukker", quantity: 500, unit: "g" }, { name: "Flødeskum", quantity: 3000, unit: "ml" }], method: ["Rist tvebakker i smør og sukker.", "Læg lag af tvebakker og æblemos.", "Top med flødeskum."] },
    "DS-030": { recipeName: "Panna Cotta", id: "DS-030", category: "Desserter", yield_net: "12.0 KG", ingredients: [{ name: "Fløde", quantity: 8000, unit: "ml" }, { name: "Sukker", quantity: 800, unit: "g" }, { name: "Vanilje", quantity: 20, unit: "g" }, { name: "Husblas", quantity: 80, unit: "g" }], method: ["Varm fløde med sukker og vanilje.", "Smelt husblas i.", "Hæld i forme.", "Køl min. 4 timer."] },
    "DS-031": { recipeName: "Tiramisu", id: "DS-031", category: "Desserter", yield_net: "10.0 KG", ingredients: [{ name: "Mascarpone", quantity: 3000, unit: "g" }, { name: "Æg", quantity: 800, unit: "g" }, { name: "Sukker", quantity: 600, unit: "g" }, { name: "Savoiardikiks", quantity: 1500, unit: "g" }, { name: "Espresso", quantity: 1500, unit: "ml" }, { name: "Kakaopulver", quantity: 100, unit: "g" }], method: ["Pisk blommer og sukker.", "Tilsæt mascarpone.", "Vend hvider i.", "Dyp kiks i kaffe.", "Lag af creme og kiks.", "Drys med kakao."] },
    "DS-032": { recipeName: "Budding m. saft", id: "DS-032", category: "Desserter", yield_net: "15.0 KG", ingredients: [{ name: "Mælk", quantity: 10000, unit: "ml" }, { name: "Buddingpulver", quantity: 600, unit: "g" }, { name: "Sukker", quantity: 800, unit: "g" }, { name: "Saft (hindbær)", quantity: 3000, unit: "ml" }], method: ["Kog budding af mælk og pulver.", "Hæld i forme.", "Køl.", "Server med saft."] },
    "DS-033": { recipeName: "Pandekager", id: "DS-033", category: "Desserter", yield_net: "100 STK", ingredients: [{ name: "Mel", quantity: 2000, unit: "g" }, { name: "Æg", quantity: 1200, unit: "g" }, { name: "Mælk", quantity: 5000, unit: "ml" }, { name: "Smør, smeltet", quantity: 300, unit: "g" }], method: ["Pisk dej glat.", "Lad hvile 30 min.", "Steg tynde pandekager.", "Server med sukker og syltetøj."] },
    "DS-034": { recipeName: "Risengrød", id: "DS-034", category: "Desserter", yield_net: "25.0 KG", ingredients: [{ name: "Grødris", quantity: 3000, unit: "g" }, { name: "Vand", quantity: 3000, unit: "ml" }, { name: "Mælk", quantity: 15000, unit: "ml" }, { name: "Smør", quantity: 500, unit: "g" }, { name: "Salt", quantity: 50, unit: "g" }], method: ["Kog ris i vand.", "Tilsæt mælk gradvist.", "Rør ofte.", "Tilsæt smør til sidst."] },
    "DS-035": { recipeName: "Risalamande", id: "DS-035", category: "Desserter", yield_net: "20.0 KG", ingredients: [{ name: "Risengrød, afkølet", quantity: 10000, unit: "g" }, { name: "Piskefløde", quantity: 5000, unit: "ml" }, { name: "Mandelflager", quantity: 500, unit: "g" }, { name: "Vanilje", quantity: 30, unit: "g" }, { name: "Kirsebærsauce", quantity: 3000, unit: "g" }], method: ["Pisk fløde.", "Bland i kold risengrød.", "Tilsæt mandler og vanilje.", "Server med kirsebærsauce."] },
};

// ===== SPRINT 4: SUPPER (Komplet) =====
export const supperKomplet: Record<string, any> = {
    "SU-001": { recipeName: "Karrysuppe", id: "SU-001", category: "Supper", yield_net: "50.0 KG", ingredients: [{ name: "Løg", quantity: 4000, unit: "g" }, { name: "Gulerødder", quantity: 4000, unit: "g" }, { name: "Æbler", quantity: 2000, unit: "g" }, { name: "Karry", quantity: 200, unit: "g" }, { name: "Hønsefond", quantity: 25000, unit: "ml" }, { name: "Fløde", quantity: 5000, unit: "ml" }], method: ["Svits grøntsager.", "Tilsæt karry.", "Tilsæt fond.", "Blend glat.", "Tilsæt fløde."] },
    "SU-002": { recipeName: "Kartoffelsuppe", id: "SU-002", category: "Supper", yield_net: "50.0 KG", ingredients: [{ name: "Kartofler", quantity: 20000, unit: "g" }, { name: "Løg", quantity: 4000, unit: "g" }, { name: "Porre", quantity: 3000, unit: "g" }, { name: "Hønsefond", quantity: 20000, unit: "ml" }, { name: "Fløde", quantity: 5000, unit: "ml" }], method: ["Svits løg og porre.", "Tilsæt kartofler og fond.", "Kog mørt.", "Blend delvist.", "Tilsæt fløde."] },
    "SU-003": { recipeName: "Klar suppe m. boller", id: "SU-003", category: "Supper", yield_net: "50.0 KG", ingredients: [{ name: "Hønsefond", quantity: 40000, unit: "ml" }, { name: "Kødboller, små", quantity: 5000, unit: "g" }, { name: "Gulerødder, i tern", quantity: 2000, unit: "g" }, { name: "Persille", quantity: 200, unit: "g" }], method: ["Kog fond op.", "Tilsæt grøntsager.", "Pocher boller i suppen.", "Pynt med persille."] },
    "SU-004": { recipeName: "Hønsekødssuppe", id: "SU-004", category: "Supper", yield_net: "50.0 KG", ingredients: [{ name: "Hønsefond", quantity: 35000, unit: "ml" }, { name: "Kylling, kogt, pillet", quantity: 5000, unit: "g" }, { name: "Gulerødder", quantity: 3000, unit: "g" }, { name: "Selleri", quantity: 2000, unit: "g" }, { name: "Melboller", quantity: 3000, unit: "g" }], method: ["Kog fond med grøntsager.", "Tilsæt kylling.", "Pocher melboller."] },
    "SU-005": { recipeName: "Hyldeblomstsuppe", id: "SU-005", category: "Supper", yield_net: "30.0 KG", ingredients: [{ name: "Hyldeblomst saft", quantity: 10000, unit: "ml" }, { name: "Vand", quantity: 15000, unit: "ml" }, { name: "Sukker", quantity: 1500, unit: "g" }, { name: "Kartoffelmel", quantity: 300, unit: "g" }], method: ["Kog saft og vand.", "Tilsæt sukker.", "Jævn.", "Server kold."] },
    "SU-006": { recipeName: "Appelsinsuppe", id: "SU-006", category: "Supper", yield_net: "25.0 KG", ingredients: [{ name: "Appelsinjuice", quantity: 15000, unit: "ml" }, { name: "Sukker", quantity: 1500, unit: "g" }, { name: "Kartoffelmel", quantity: 250, unit: "g" }], method: ["Kog juice med sukker.", "Jævn.", "Server kold med flødeskum."] },
    "SU-007": { recipeName: "Koldskål", id: "SU-007", category: "Supper", yield_net: "25.0 KG", ingredients: [{ name: "Kærnemælk", quantity: 15000, unit: "ml" }, { name: "Æggeblommer", quantity: 600, unit: "g" }, { name: "Sukker", quantity: 800, unit: "g" }, { name: "Vanilje", quantity: 20, unit: "g" }, { name: "Citronsaft", quantity: 200, unit: "ml" }], method: ["Pisk blommer og sukker.", "Tilsæt kærnemælk.", "Smag til med citron og vanilje.", "Køl.", "Server med kammerjunkere."] },
};

// ===== SPRINT 5: TILBEHØR & KULHYDRATER =====
export const tilbehoerOgKulhydrater: Record<string, any> = {
    // KULHYDRATER
    "KH-001": { recipeName: "Kogte kartofler", id: "KH-001", category: "Kulhydrater", yield_net: "30.0 KG", ingredients: [{ name: "Kartofler", quantity: 30000, unit: "g" }, { name: "Salt", quantity: 200, unit: "g" }], method: ["Skræl kartofler.", "Kog i saltvand.", "Dræn når møre."] },
    "KH-002": { recipeName: "Flødekartofler", id: "KH-002", category: "Kulhydrater", yield_net: "25.0 KG", ingredients: [{ name: "Kartofler, i skiver", quantity: 18000, unit: "g" }, { name: "Fløde", quantity: 5000, unit: "ml" }, { name: "Mælk", quantity: 3000, unit: "ml" }, { name: "Hvidløg", quantity: 100, unit: "g" }, { name: "Ost", quantity: 1500, unit: "g" }], method: ["Læg kartofler i lag.", "Bland fløde, mælk, hvidløg.", "Hæld over.", "Top med ost.", "Bag ved 180°C i 60 min."] },
    "KH-003": { recipeName: "Brasede kartofler", id: "KH-003", category: "Kulhydrater", yield_net: "25.0 KG", ingredients: [{ name: "Kartofler", quantity: 20000, unit: "g" }, { name: "Smør", quantity: 2000, unit: "g" }, { name: "Fond", quantity: 3000, unit: "ml" }], method: ["Skræl og skær kartofler.", "Brun i smør.", "Tilsæt fond.", "Bag ved 180°C til møre."] },
    "KH-004": { recipeName: "Stegte kartofler", id: "KH-004", category: "Kulhydrater", yield_net: "25.0 KG", ingredients: [{ name: "Kartofler, kogte", quantity: 22000, unit: "g" }, { name: "Smør/Olie", quantity: 3000, unit: "g" }], method: ["Skær i skiver.", "Steg i smør til sprøde."] },
    "KH-005": { recipeName: "Brunede kartofler", id: "KH-005", category: "Kulhydrater", yield_net: "25.0 KG", ingredients: [{ name: "Små kartofler, kogte", quantity: 20000, unit: "g" }, { name: "Sukker", quantity: 1500, unit: "g" }, { name: "Smør", quantity: 1500, unit: "g" }], method: ["Lav karamel af sukker.", "Tilsæt smør.", "Vend kartofler i."] },
    "KH-006": { recipeName: "Nye kartofler", id: "KH-006", category: "Kulhydrater", yield_net: "25.0 KG", ingredients: [{ name: "Nye kartofler", quantity: 25000, unit: "g" }, { name: "Smør", quantity: 500, unit: "g" }, { name: "Persille", quantity: 200, unit: "g" }], method: ["Skog i saltvand.", "Vend i smør.", "Drys med persille."] },
    "KH-007": { recipeName: "Kogte ris", id: "KH-007", category: "Kulhydrater", yield_net: "15.0 KG", ingredients: [{ name: "Ris", quantity: 6000, unit: "g" }, { name: "Vand", quantity: 12000, unit: "ml" }, { name: "Salt", quantity: 60, unit: "g" }], method: ["Kog vand.", "Tilsæt ris.", "Kog i 12 min.", "Dræn."] },
    "KH-008": { recipeName: "Pasta", id: "KH-008", category: "Kulhydrater", yield_net: "15.0 KG", ingredients: [{ name: "Pasta", quantity: 8000, unit: "g" }, { name: "Vand", quantity: 20000, unit: "ml" }, { name: "Salt", quantity: 100, unit: "g" }], method: ["Kog vand.", "Tilsæt pasta.", "Kog al dente.", "Dræn."] },
    "KH-009": { recipeName: "Tarteletter (skaller)", id: "KH-009", category: "Kulhydrater", yield_net: "100 STK", ingredients: [{ name: "Mørdej", quantity: 5000, unit: "g" }], method: ["Rul dej ud.", "Beklæd forme.", "Blindbag ved 180°C.", "Afkøl."] },
    // TILBEHØR
    "TB-001": { recipeName: "Agurkesalat", id: "TB-001", category: "Tilbehør", yield_net: "10.0 KG", ingredients: [{ name: "Agurk, i skiver", quantity: 8000, unit: "g" }, { name: "Eddike", quantity: 500, unit: "ml" }, { name: "Sukker", quantity: 500, unit: "g" }, { name: "Dild", quantity: 100, unit: "g" }], method: ["Skær agurk tyndt.", "Bland eddike og sukker.", "Hæld over agurk.", "Tilsæt dild."] },
    "TB-002": { recipeName: "Råkost", id: "TB-002", category: "Tilbehør", yield_net: "12.0 KG", ingredients: [{ name: "Gulerødder, revet", quantity: 5000, unit: "g" }, { name: "Hvidkål, snittet", quantity: 4000, unit: "g" }, { name: "Rosiner", quantity: 500, unit: "g" }, { name: "Dressing", quantity: 2000, unit: "g" }], method: ["Riv gulerødder.", "Snit kål.", "Bland med rosiner og dressing."] },
    "TB-003": { recipeName: "Waldorfsalat", id: "TB-003", category: "Tilbehør", yield_net: "10.0 KG", ingredients: [{ name: "Æbler, i tern", quantity: 3000, unit: "g" }, { name: "Selleri, i tern", quantity: 2000, unit: "g" }, { name: "Valnødder", quantity: 500, unit: "g" }, { name: "Mayonnaise", quantity: 2000, unit: "g" }, { name: "Fløde", quantity: 500, unit: "ml" }], method: ["Skær æbler og selleri.", "Riv mayonnaise med fløde.", "Bland alt.", "Drys med valnødder."] },
    "TB-004": { recipeName: "Coleslaw", id: "TB-004", category: "Tilbehør", yield_net: "12.0 KG", ingredients: [{ name: "Hvidkål, finsnittet", quantity: 6000, unit: "g" }, { name: "Gulerødder, revet", quantity: 2000, unit: "g" }, { name: "Mayonnaise", quantity: 3000, unit: "g" }, { name: "Eddike", quantity: 200, unit: "ml" }], method: ["Snit kål.", "Riv gulerødder.", "Bland med mayo og eddike."] },
    "TB-005": { recipeName: "Rødkål", id: "TB-005", category: "Tilbehør", yield_net: "15.0 KG", ingredients: [{ name: "Rødkål", quantity: 12000, unit: "g" }, { name: "Sukker", quantity: 800, unit: "g" }, { name: "Eddike", quantity: 500, unit: "ml" }, { name: "Ribsgelé", quantity: 500, unit: "g" }, { name: "Smør", quantity: 300, unit: "g" }], method: ["Snit rødkål.", "Stev med sukker og eddike.", "Tilsæt gelé og smør."] },
    "TB-006": { recipeName: "Surkål", id: "TB-006", category: "Tilbehør", yield_net: "15.0 KG", ingredients: [{ name: "Hvidkål", quantity: 12000, unit: "g" }, { name: "Eddike", quantity: 500, unit: "ml" }, { name: "Sukker", quantity: 1000, unit: "g" }, { name: "Kommen", quantity: 30, unit: "g" }], method: ["Snit kål.", "Bland med eddike, sukker og kommen.", "Lad trække."] },
    "TB-007": { recipeName: "Rødbeder", id: "TB-007", category: "Tilbehør", yield_net: "10.0 KG", ingredients: [{ name: "Rødbeder", quantity: 10000, unit: "g" }, { name: "Eddike", quantity: 500, unit: "ml" }, { name: "Sukker", quantity: 500, unit: "g" }], method: ["Kog rødbeder.", "Skræl og skær.", "Læg i eddike/sukker-lage."] },
    "TB-008": { recipeName: "Dampet broccoli", id: "TB-008", category: "Tilbehør", yield_net: "10.0 KG", ingredients: [{ name: "Broccoli", quantity: 10000, unit: "g" }, { name: "Salt", quantity: 50, unit: "g" }], method: ["Del i buketter.", "Damp 4-6 min.", "Skal være sprød."] },
    "TB-009": { recipeName: "Bønner (grønne)", id: "TB-009", category: "Tilbehør", yield_net: "10.0 KG", ingredients: [{ name: "Grønne bønner", quantity: 10000, unit: "g" }, { name: "Smør", quantity: 300, unit: "g" }], method: ["Damp eller kog bønner.", "Vend i smør."] },
    "TB-010": { recipeName: "Ærter", id: "TB-010", category: "Tilbehør", yield_net: "8.0 KG", ingredients: [{ name: "Ærter, frosne", quantity: 8000, unit: "g" }, { name: "Smør", quantity: 200, unit: "g" }], method: ["Kog ærter.", "Vend i smør."] },
    "TB-011": { recipeName: "Tomatsalat", id: "TB-011", category: "Tilbehør", yield_net: "10.0 KG", ingredients: [{ name: "Tomater", quantity: 8000, unit: "g" }, { name: "Løg", quantity: 1000, unit: "g" }, { name: "Olivenolie", quantity: 500, unit: "ml" }, { name: "Basilikum", quantity: 100, unit: "g" }], method: ["Skær tomater.", "Skær løg.", "Bland med olie og basilikum."] },
    "TB-012": { recipeName: "Rabarberkompot", id: "TB-012", category: "Tilbehør", yield_net: "10.0 KG", ingredients: [{ name: "Rabarber", quantity: 8000, unit: "g" }, { name: "Sukker", quantity: 2000, unit: "g" }], method: ["Skær rabarber.", "Kog med sukker.", "Afkøl."] },
    "TB-013": { recipeName: "Bløde løg", id: "TB-013", category: "Tilbehør", yield_net: "8.0 KG", ingredients: [{ name: "Løg, i ringe", quantity: 8000, unit: "g" }, { name: "Smør", quantity: 500, unit: "g" }], method: ["Steg løg langsomt.", "Til bløde og gyldne."] },
    "TB-014": { recipeName: "Mango chutney", id: "TB-014", category: "Tilbehør", yield_net: "5.0 KG", ingredients: [{ name: "Mango", quantity: 3000, unit: "g" }, { name: "Sukker", quantity: 1000, unit: "g" }, { name: "Eddike", quantity: 500, unit: "ml" }, { name: "Ingefær", quantity: 100, unit: "g" }], method: ["Skær mango.", "Kog alt sammen.", "Til tyk konsistens."] },
    "TB-015": { recipeName: "Tzatziki", id: "TB-015", category: "Tilbehør", yield_net: "8.0 KG", ingredients: [{ name: "Yoghurt", quantity: 5000, unit: "g" }, { name: "Agurk, revet", quantity: 2000, unit: "g" }, { name: "Hvidløg", quantity: 100, unit: "g" }, { name: "Mynte", quantity: 50, unit: "g" }], method: ["Dræn agurk.", "Bland med yoghurt.", "Tilsæt hvidløg og mynte."] },
};

// Export all Sprint 3-5 recipes
export const allSprintRecipes = {
    ...desserterKomplet,
    ...supperKomplet,
    ...tilbehoerOgKulhydrater,
};
