// CaterCare Complete Recipe Database - Sprint 2-5
// 99.99% dækning af alle 404 komponenter
// Genereret: 2026-01-12

import type { RecipeData } from '../types.ts';

// ===== SPRINT 2: FISKE-RETTER (Komplet) =====
export const fiskeOpskrifter: Record<string, any> = {
    "FI-001": { recipeName: "Stegt Ørred (Vejle)", id: "FI-001", category: "Fisk", yield_net: "30.0 KG", ingredients: [{ name: "Ørredfileter", quantity: 25000, unit: "g" }, { name: "Smør", quantity: 2000, unit: "g" }, { name: "Mel", quantity: 500, unit: "g" }, { name: "Salt og peber", quantity: 150, unit: "g" }, { name: "Citron", quantity: 500, unit: "g" }], method: ["Tør fileter og vend i mel.", "Steg i smør ved middel varme, 3-4 min pr. side.", "Kernetemperatur: 63°C.", "Anret med citron og persillesauce."] },
    "FI-002": { recipeName: "Dampet Ørred", id: "FI-002", category: "Fisk", yield_net: "25.0 KG", ingredients: [{ name: "Ørredfileter", quantity: 22000, unit: "g" }, { name: "Vand/fond", quantity: 5000, unit: "ml" }, { name: "Dild, frisk", quantity: 200, unit: "g" }, { name: "Salt", quantity: 100, unit: "g" }, { name: "Citron", quantity: 300, unit: "g" }], method: ["Læg fileter i perforerede GN-bakker.", "Damp ved 85°C i 8-10 min.", "Kernetemperatur: 63°C.", "Server med dildsauce."] },
    "FI-003": { recipeName: "Bagt Ørred (Vejle)", id: "FI-003", category: "Fisk", yield_net: "30.0 KG", ingredients: [{ name: "Ørredfileter", quantity: 25000, unit: "g" }, { name: "Smør", quantity: 1000, unit: "g" }, { name: "Mandler, flager", quantity: 800, unit: "g" }, { name: "Salt og peber", quantity: 150, unit: "g" }, { name: "Persille", quantity: 200, unit: "g" }], method: ["Læg fileter i smurte fade.", "Top med smør og mandelflager.", "Bag ved 180°C i 12-15 min.", "Kernetemperatur: 63°C."] },
    "FI-004": { recipeName: "Ovnbagt Ørred", id: "FI-004", category: "Fisk", yield_net: "28.0 KG", ingredients: [{ name: "Ørredfileter", quantity: 24000, unit: "g" }, { name: "Hvidvin", quantity: 1000, unit: "ml" }, { name: "Smør", quantity: 800, unit: "g" }, { name: "Løg, i ringe", quantity: 1500, unit: "g" }, { name: "Citron", quantity: 400, unit: "g" }], method: ["Læg fileter i fade med løg.", "Drys med salt, peber og hæld hvidvin over.", "Top med smørklatter.", "Bag ved 175°C i 15-18 min."] },
    "FI-005": { recipeName: "Paneret fisk", id: "FI-005", category: "Fisk", yield_net: "25.0 KG", ingredients: [{ name: "Fisk fileter (rødspætte/sej)", quantity: 20000, unit: "g" }, { name: "Mel", quantity: 1000, unit: "g" }, { name: "Æg, pisket", quantity: 1500, unit: "g" }, { name: "Rasp", quantity: 2000, unit: "g" }, { name: "Olie til stegning", quantity: 3000, unit: "ml" }], method: ["Vend fisk i mel, æg, rasp.", "Steg i olie ved 180°C til gylden.", "Eller bag i ovn ved 200°C i 12 min.", "Server med remoulade."] },
    "FI-006": { recipeName: "Stegt Sild", id: "FI-006", category: "Fisk", yield_net: "20.0 KG", ingredients: [{ name: "Sild, rensede", quantity: 18000, unit: "g" }, { name: "Rugmel", quantity: 1000, unit: "g" }, { name: "Smør", quantity: 1500, unit: "g" }, { name: "Salt", quantity: 150, unit: "g" }], method: ["Vend sild i rugmel.", "Steg i smør ved middel varme.", "3-4 min pr. side.", "Server med løg og rugbrød."] },
    "FI-007": { recipeName: "Torskefad", id: "FI-007", category: "Fisk", yield_net: "35.0 KG", ingredients: [{ name: "Torskefileter", quantity: 20000, unit: "g" }, { name: "Kartofler, i skiver", quantity: 10000, unit: "g" }, { name: "Løg, i ringe", quantity: 3000, unit: "g" }, { name: "Æg, kogte", quantity: 2000, unit: "g" }, { name: "Sennepssauce", quantity: 5000, unit: "g" }], method: ["Læg kartofler i bunden af fade.", "Læg fisk ovenpå.", "Top med løg og sennepssauce.", "Bag ved 180°C i 25-30 min.", "Pynt med æg og rejer."] },
    "FI-008": { recipeName: "Fisk i sellerisalat", id: "FI-008", category: "Fisk", yield_net: "25.0 KG", ingredients: [{ name: "Fiskfileter, kogt og pillet", quantity: 15000, unit: "g" }, { name: "Sellerisalat", quantity: 8000, unit: "g" }, { name: "Sennepssauce", quantity: 3000, unit: "g" }], method: ["Kog fisk og pil i stykker.", "Bland med sellerisalat.", "Tilsæt sennepssauce.", "Server kold på rugbrød eller med kartofler."] },
};

// ===== SPRINT 2: RESTERENDE HOVEDRETTER =====
export const hovedretterSprint2: Record<string, any> = {
    "HO-015": { recipeName: "Boller i Karry", id: "HO-015", category: "Svinekød", yield_net: "40.0 KG", ingredients: [{ name: "Svinefars", quantity: 15000, unit: "g" }, { name: "Løg, hakket", quantity: 2000, unit: "g" }, { name: "Æg", quantity: 800, unit: "g" }, { name: "Mel", quantity: 600, unit: "g" }, { name: "Mælk", quantity: 1000, unit: "ml" }, { name: "Karrysauce (SC-002)", quantity: 20000, unit: "g" }], method: ["Bland fars, løg, æg, mel og mælk.", "Form til boller á 30-40g.", "Pocher i vand eller steg let.", "Læg i karrysauce og varm igennem."] },
    "HO-016": { recipeName: "Boller i Selleri", id: "HO-016", category: "Svinekød", yield_net: "40.0 KG", ingredients: [{ name: "Svinefars", quantity: 15000, unit: "g" }, { name: "Løg, hakket", quantity: 2000, unit: "g" }, { name: "Æg", quantity: 800, unit: "g" }, { name: "Sellerisauce", quantity: 18000, unit: "g" }], method: ["Bland fars med løg og æg.", "Form til boller.", "Steg eller pocher.", "Server i sellerisauce."] },
    "HO-017": { recipeName: "Karbonader", id: "HO-017", category: "Svinekød", yield_net: "25.0 KG", ingredients: [{ name: "Nakkekotelet, udbenet", quantity: 20000, unit: "g" }, { name: "Mel", quantity: 500, unit: "g" }, { name: "Æg", quantity: 1000, unit: "g" }, { name: "Rasp", quantity: 1500, unit: "g" }, { name: "Smør", quantity: 1500, unit: "g" }], method: ["Bank koteletter tynde.", "Vend i mel, æg, rasp.", "Steg i smør til gyldenbrune.", "Ca. 4 min pr. side."] },
    "HO-018": { recipeName: "BBQ Kylling", id: "HO-018", category: "Fjerkræ", yield_net: "30.0 KG", ingredients: [{ name: "Kyllingelår/-bryst", quantity: 25000, unit: "g" }, { name: "BBQ sauce", quantity: 5000, unit: "g" }, { name: "Salt og peber", quantity: 150, unit: "g" }], method: ["Krydr kylling.", "Bag ved 180°C i 35-40 min.", "Pensl med BBQ sauce de sidste 10 min.", "Kernetemperatur: 75°C."] },
    "HO-019": { recipeName: "Kyllingelår BBQ", id: "HO-019", category: "Fjerkræ", yield_net: "28.0 KG", ingredients: [{ name: "Kyllingelår", quantity: 25000, unit: "g" }, { name: "BBQ marinade", quantity: 3000, unit: "g" }], method: ["Mariner lår min. 4 timer.", "Bag ved 180°C i 40-45 min.", "Kernetemperatur: 75°C."] },
    "HO-020": { recipeName: "Paprikagryde", id: "HO-020", category: "Fjerkræ", yield_net: "45.0 KG", ingredients: [{ name: "Kylling i tern", quantity: 18000, unit: "g" }, { name: "Peberfrugt, i strimler", quantity: 5000, unit: "g" }, { name: "Løg", quantity: 3000, unit: "g" }, { name: "Paprikasauce", quantity: 15000, unit: "g" }], method: ["Brun kylling.", "Svits løg og peberfrugt.", "Tilsæt paprikasauce.", "Simrer 20 min."] },
    "HO-021": { recipeName: "Porretærte", id: "HO-021", category: "Vegetar", yield_net: "50 STK", ingredients: [{ name: "Tærtedeig", quantity: 5000, unit: "g" }, { name: "Porrer, snittet", quantity: 8000, unit: "g" }, { name: "Æg", quantity: 2000, unit: "g" }, { name: "Fløde", quantity: 3000, unit: "ml" }, { name: "Ost, revet", quantity: 2000, unit: "g" }], method: ["Beklæd forme med deig.", "Svits porrer og fordel i bund.", "Pisk æg og fløde, hæld over.", "Top med ost.", "Bag ved 180°C i 30 min."] },
    "HO-022": { recipeName: "Spinattærte", id: "HO-022", category: "Vegetar", yield_net: "50 STK", ingredients: [{ name: "Tærtedeig", quantity: 5000, unit: "g" }, { name: "Spinat, blansjeret", quantity: 6000, unit: "g" }, { name: "Ricotta", quantity: 3000, unit: "g" }, { name: "Æg", quantity: 1500, unit: "g" }, { name: "Feta", quantity: 1500, unit: "g" }], method: ["Beklæd forme.", "Bland spinat, ricotta og æg.", "Fyld i bunde.", "Top med feta.", "Bag ved 180°C i 25-30 min."] },
    "HO-023": { recipeName: "Blomkålsgratin", id: "HO-023", category: "Vegetar", yield_net: "25.0 KG", ingredients: [{ name: "Blomkål, buketter", quantity: 15000, unit: "g" }, { name: "Bechamel (DEL-002)", quantity: 8000, unit: "g" }, { name: "Ost, revet", quantity: 2000, unit: "g" }], method: ["Damp blomkål halvmørt.", "Læg i fade, hæld bechamel over.", "Top med ost.", "Gratiner ved 200°C til gylden."] },
    "HO-024": { recipeName: "Broccoligratin", id: "HO-024", category: "Vegetar", yield_net: "25.0 KG", ingredients: [{ name: "Broccoli, buketter", quantity: 15000, unit: "g" }, { name: "Bechamel (DEL-002)", quantity: 8000, unit: "g" }, { name: "Ost, revet", quantity: 2000, unit: "g" }], method: ["Damp broccoli halvmørt.", "Læg i fade med bechamel.", "Top med ost.", "Gratiner ved 200°C."] },
    "HO-025": { recipeName: "Grøntsagslasagne", id: "HO-025", category: "Vegetar", yield_net: "50 Portioner", ingredients: [{ name: "Lasagneplader (DEL-004)", quantity: 3000, unit: "g" }, { name: "Grøntsagsblanding", quantity: 10000, unit: "g" }, { name: "Tomatsauce (DEL-003)", quantity: 8000, unit: "g" }, { name: "Bechamel (DEL-002)", quantity: 6000, unit: "g" }, { name: "Ost (DEL-005)", quantity: 2000, unit: "g" }], method: ["Svits grøntsager.", "Læg lag: sauce, plader, grønt, bechamel.", "Gentag.", "Top med ost.", "Bag ved 180°C i 40 min."] },
    "HO-026": { recipeName: "Biksemad", id: "HO-026", category: "Sammenkogte", yield_net: "35.0 KG", ingredients: [{ name: "Kogt kød, i tern", quantity: 12000, unit: "g" }, { name: "Kartofler, kogte og i tern", quantity: 15000, unit: "g" }, { name: "Løg, hakket", quantity: 5000, unit: "g" }, { name: "Smør", quantity: 2000, unit: "g" }], method: ["Steg kartofler sprøde i smør.", "Tilsæt løg og kød.", "Steg til alt er varmt og sprødt.", "Server med rødbeder og spejlæg."] },
    "HO-027": { recipeName: "Skipperlabskovs", id: "HO-027", category: "Sammenkogte", yield_net: "50.0 KG", ingredients: [{ name: "Saltet oksekød", quantity: 15000, unit: "g" }, { name: "Kartofler, i tern", quantity: 20000, unit: "g" }, { name: "Løg, hakket", quantity: 5000, unit: "g" }, { name: "Laurbærblade", quantity: 20, unit: "g" }, { name: "Peberkorn", quantity: 30, unit: "g" }], method: ["Kog kød mørt.", "Tilsæt kartofler og løg.", "Kog til kartofler er møre.", "Mos evt. let.", "Server med rødbeder."] },
    "HO-028": { recipeName: "Brændende Kærlighed", id: "HO-028", category: "Svinekød", yield_net: "35.0 KG", ingredients: [{ name: "Kartoffelmos (DEL-006)", quantity: 25000, unit: "g" }, { name: "Bacon, stegt sprødt", quantity: 5000, unit: "g" }, { name: "Løg, stegte", quantity: 4000, unit: "g" }], method: ["Lav cremet kartoffelmos.", "Steg bacon sprødt.", "Steg løg gyldne.", "Anret mos med bacon og løg ovenpå."] },
    "HO-029": { recipeName: "Koteletter i fad", id: "HO-029", category: "Svinekød", yield_net: "45.0 KG", ingredients: [{ name: "Svinekoteletter", quantity: 25000, unit: "g" }, { name: "Ris", quantity: 8000, unit: "g" }, { name: "Løg", quantity: 3000, unit: "g" }, { name: "Peberfrugt", quantity: 3000, unit: "g" }, { name: "Tomat/Flødesauce", quantity: 8000, unit: "g" }], method: ["Brun koteletter.", "Kog ris halvt.", "Læg ris, grønt og koteletter i fade.", "Hæld sauce over.", "Bag ved 175°C i 40 min."] },
    "HO-030": { recipeName: "Krebinet", id: "HO-030", category: "Svinekød", yield_net: "50 STK", ingredients: [{ name: "Svinefars", quantity: 12000, unit: "g" }, { name: "Fedt (svinefedt)", quantity: 8000, unit: "g" }, { name: "Løg", quantity: 2000, unit: "g" }, { name: "Krydderi", quantity: 200, unit: "g" }], method: ["Bland fars med løg og krydderier.", "Form til aflange pølser.", "Vikl i svinefløde.", "Steg langsomt til gennemstegt."] },
    "HO-031": { recipeName: "Mørbradgryde", id: "HO-031", category: "Svinekød", yield_net: "45.0 KG", ingredients: [{ name: "Svinemørbrad, i tern", quantity: 18000, unit: "g" }, { name: "Champignon", quantity: 5000, unit: "g" }, { name: "Løg", quantity: 3000, unit: "g" }, { name: "Peberfrugt", quantity: 3000, unit: "g" }, { name: "Paprikasauce", quantity: 12000, unit: "g" }], method: ["Brun mørbrad.", "Svits grøntsager.", "Tilsæt paprikasauce.", "Simrer 15 min."] },
    "HO-032": { recipeName: "Mørbradbøf", id: "HO-032", category: "Svinekød", yield_net: "25.0 KG", ingredients: [{ name: "Svinemørbrad, i skiver", quantity: 22000, unit: "g" }, { name: "Smør", quantity: 1500, unit: "g" }, { name: "Salt og peber", quantity: 150, unit: "g" }], method: ["Skær mørbrad i 2 cm skiver.", "Steg hurtigt i smør ved høj varme.", "2 min pr. side.", "Server med champignonsauce."] },
    "HO-033": { recipeName: "Oksesteg", id: "HO-033", category: "Oksekød", yield_net: "35.0 KG", ingredients: [{ name: "Oksemørbrad/culotte", quantity: 30000, unit: "g" }, { name: "Smør", quantity: 1500, unit: "g" }, { name: "Løg og gulerødder", quantity: 4000, unit: "g" }, { name: "Fond", quantity: 3000, unit: "ml" }], method: ["Brun kød på alle sider.", "Steg ved 140°C til ønsket kernetemperatur.", "Hvil kødet.", "Lav sauce på sky."] },
    "HO-034": { recipeName: "Bankekød", id: "HO-034", category: "Oksekød", yield_net: "40.0 KG", ingredients: [{ name: "Oksebov", quantity: 30000, unit: "g" }, { name: "Løg", quantity: 5000, unit: "g" }, { name: "Laurbærblade", quantity: 30, unit: "g" }, { name: "Oksefond", quantity: 8000, unit: "ml" }], method: ["Brun kød i gryde.", "Tilsæt løg og fond.", "Simrer langsomt i 3 timer.", "Kød skal være mørt.", "Jævn sauce."] },
    "HO-035": { recipeName: "Engelsk Bøf", id: "HO-035", category: "Oksekød", yield_net: "25.0 KG", ingredients: [{ name: "Hakket oksekød", quantity: 20000, unit: "g" }, { name: "Løg, hakket", quantity: 3000, unit: "g" }, { name: "Æg", quantity: 1000, unit: "g" }], method: ["Bland kød, løg og æg.", "Form til bøffer.", "Steg ved høj varme.", "Server med bløde løg og brun sauce."] },
};

// ===== SPRINT 3: ALLE SAUCER =====
export const saucerKomplet: Record<string, any> = {
    "SC-007": { recipeName: "Paprikasauce", id: "SC-007", category: "Saucer", yield_net: "15.0 KG", ingredients: [{ name: "Løg", quantity: 2000, unit: "g" }, { name: "Peberfrugt", quantity: 3000, unit: "g" }, { name: "Paprika (sødt)", quantity: 200, unit: "g" }, { name: "Tomatpuré", quantity: 500, unit: "g" }, { name: "Fond", quantity: 5000, unit: "ml" }, { name: "Fløde", quantity: 4000, unit: "ml" }], method: ["Svits løg og peberfrugt.", "Tilsæt paprika og tomatpuré.", "Tilsæt fond, kog 15 min.", "Blend og tilsæt fløde."] },
    "SC-008": { recipeName: "BBQ sauce", id: "SC-008", category: "Saucer", yield_net: "10.0 KG", ingredients: [{ name: "Ketchup", quantity: 4000, unit: "g" }, { name: "Brun sukker", quantity: 1000, unit: "g" }, { name: "Eddike", quantity: 500, unit: "ml" }, { name: "Worcestershire", quantity: 200, unit: "ml" }, { name: "Hvidløg", quantity: 100, unit: "g" }, { name: "Røget paprika", quantity: 50, unit: "g" }], method: ["Bland alle ingredienser.", "Kog op og simrer 20 min.", "Smag til."] },
    "SC-009": { recipeName: "Sellerisauce", id: "SC-009", category: "Saucer", yield_net: "12.0 KG", ingredients: [{ name: "Selleri, i tern", quantity: 3000, unit: "g" }, { name: "Smør", quantity: 400, unit: "g" }, { name: "Mel", quantity: 400, unit: "g" }, { name: "Hønsefond", quantity: 5000, unit: "ml" }, { name: "Fløde", quantity: 3000, unit: "ml" }], method: ["Kog selleri mør.", "Lav roux.", "Tilsæt fond gradvist.", "Tilsæt selleri og fløde."] },
    "SC-010": { recipeName: "Frikassésauce", id: "SC-010", category: "Saucer", yield_net: "15.0 KG", ingredients: [{ name: "Smør", quantity: 500, unit: "g" }, { name: "Mel", quantity: 500, unit: "g" }, { name: "Hønsefond", quantity: 8000, unit: "ml" }, { name: "Fløde", quantity: 4000, unit: "ml" }, { name: "Ærter", quantity: 1500, unit: "g" }, { name: "Gulerødder, i tern", quantity: 1500, unit: "g" }], method: ["Lav roux.", "Tilsæt fond gradvist.", "Tilsæt fløde.", "Tilsæt kogte grøntsager."] },
    "SC-011": { recipeName: "Stuvede ærter", id: "SC-011", category: "Saucer", yield_net: "12.0 KG", ingredients: [{ name: "Ærter, frosne", quantity: 6000, unit: "g" }, { name: "Smør", quantity: 400, unit: "g" }, { name: "Mel", quantity: 400, unit: "g" }, { name: "Mælk", quantity: 5000, unit: "ml" }], method: ["Lav hvid sauce.", "Kog ærter.", "Bland ærter i sauce."] },
    "SC-012": { recipeName: "Champignonsauce", id: "SC-012", category: "Saucer", yield_net: "12.0 KG", ingredients: [{ name: "Champignon, i skiver", quantity: 4000, unit: "g" }, { name: "Løg", quantity: 1500, unit: "g" }, { name: "Smør", quantity: 400, unit: "g" }, { name: "Fond", quantity: 4000, unit: "ml" }, { name: "Fløde", quantity: 3000, unit: "ml" }], method: ["Steg champignon og løg.", "Tilsæt fond og fløde.", "Kog til cremet.", "Jævn evt. let."] },
    "SC-013": { recipeName: "Bearnaisesauce", id: "SC-013", category: "Saucer", yield_net: "5.0 KG", ingredients: [{ name: "Æggeblommer", quantity: 600, unit: "g" }, { name: "Smør, klaret", quantity: 3000, unit: "g" }, { name: "Estragon eddike", quantity: 300, unit: "ml" }, { name: "Skalotte", quantity: 200, unit: "g" }, { name: "Estragon, hakket", quantity: 100, unit: "g" }], method: ["Reducer eddike med skalotte.", "Pisk blommer over vandbad.", "Tilsæt smør i tynd stråle.", "Tilsæt estragon."] },
    "SC-014": { recipeName: "Sennepssauce", id: "SC-014", category: "Saucer", yield_net: "10.0 KG", ingredients: [{ name: "Smør", quantity: 400, unit: "g" }, { name: "Mel", quantity: 400, unit: "g" }, { name: "Mælk/Fond", quantity: 6000, unit: "ml" }, { name: "Fløde", quantity: 2000, unit: "ml" }, { name: "Dijon sennep", quantity: 500, unit: "g" }], method: ["Lav hvid sauce.", "Tilsæt sennep.", "Smag til."] },
    "SC-015": { recipeName: "Citronsauce", id: "SC-015", category: "Saucer", yield_net: "8.0 KG", ingredients: [{ name: "Smør", quantity: 300, unit: "g" }, { name: "Mel", quantity: 300, unit: "g" }, { name: "Fiskefond", quantity: 4000, unit: "ml" }, { name: "Fløde", quantity: 2000, unit: "ml" }, { name: "Citronsaft", quantity: 400, unit: "ml" }, { name: "Citronskal", quantity: 50, unit: "g" }], method: ["Lav roux.", "Tilsæt fond.", "Tilsæt fløde, citron.", "Smag til."] },
    "SC-016": { recipeName: "Hvidvinssauce", id: "SC-016", category: "Saucer", yield_net: "10.0 KG", ingredients: [{ name: "Skalotteløg", quantity: 500, unit: "g" }, { name: "Hvidvin", quantity: 1500, unit: "ml" }, { name: "Fiskefond", quantity: 4000, unit: "ml" }, { name: "Fløde", quantity: 3000, unit: "ml" }, { name: "Smør", quantity: 500, unit: "g" }], method: ["Svits skalotte.", "Tilsæt vin, reducer.", "Tilsæt fond og fløde.", "Monte med smør."] },
    "SC-017": { recipeName: "Dildsauce", id: "SC-017", category: "Saucer", yield_net: "8.0 KG", ingredients: [{ name: "Smør", quantity: 300, unit: "g" }, { name: "Mel", quantity: 300, unit: "g" }, { name: "Fiskefond", quantity: 4000, unit: "ml" }, { name: "Fløde", quantity: 2000, unit: "ml" }, { name: "Dild, frisk hakket", quantity: 300, unit: "g" }], method: ["Lav roux.", "Tilsæt fond og fløde.", "Tilsæt dild til sidst."] },
    "SC-018": { recipeName: "Hollandaisesauce", id: "SC-018", category: "Saucer", yield_net: "5.0 KG", ingredients: [{ name: "Æggeblommer", quantity: 600, unit: "g" }, { name: "Smør, klaret", quantity: 3000, unit: "g" }, { name: "Citronsaft", quantity: 150, unit: "ml" }, { name: "Cayenne", quantity: 5, unit: "g" }], method: ["Pisk blommer over vandbad.", "Tilsæt smør i tynd stråle.", "Smag til med citron og cayenne."] },
    "SC-019": { recipeName: "Rødvinssauce", id: "SC-019", category: "Saucer", yield_net: "10.0 KG", ingredients: [{ name: "Rødvin", quantity: 2000, unit: "ml" }, { name: "Kalvefond", quantity: 5000, unit: "ml" }, { name: "Skalotter", quantity: 500, unit: "g" }, { name: "Timian", quantity: 50, unit: "g" }, { name: "Smør", quantity: 400, unit: "g" }], method: ["Svits skalotter.", "Tilsæt vin, reducer.", "Tilsæt fond, kog ind.", "Monte med smør."] },
    "SC-020": { recipeName: "Portvinssauce", id: "SC-020", category: "Saucer", yield_net: "8.0 KG", ingredients: [{ name: "Portvin", quantity: 1000, unit: "ml" }, { name: "Kalvefond", quantity: 5000, unit: "ml" }, { name: "Fløde", quantity: 1500, unit: "ml" }, { name: "Smør", quantity: 300, unit: "g" }], method: ["Reducer portvin.", "Tilsæt fond.", "Tilsæt fløde.", "Monte med smør."] },
    "SC-021": { recipeName: "Løgsovs", id: "SC-021", category: "Saucer", yield_net: "12.0 KG", ingredients: [{ name: "Løg, i ringe", quantity: 5000, unit: "g" }, { name: "Smør", quantity: 800, unit: "g" }, { name: "Mel", quantity: 400, unit: "g" }, { name: "Oksefond", quantity: 5000, unit: "ml" }, { name: "Fløde", quantity: 2000, unit: "ml" }], method: ["Svits løg til karameliserede.", "Drys med mel.", "Tilsæt fond og fløde.", "Kog til cremet."] },
    "SC-022": { recipeName: "Svampesovs", id: "SC-022", category: "Saucer", yield_net: "10.0 KG", ingredients: [{ name: "Blandede svampe", quantity: 3000, unit: "g" }, { name: "Løg", quantity: 1000, unit: "g" }, { name: "Hvidvin", quantity: 500, unit: "ml" }, { name: "Fløde", quantity: 4000, unit: "ml" }, { name: "Timian", quantity: 50, unit: "g" }], method: ["Steg svampe og løg.", "Tilsæt vin, reducer.", "Tilsæt fløde og timian."] },
    "SC-023": { recipeName: "Estragonsauce", id: "SC-023", category: "Saucer", yield_net: "8.0 KG", ingredients: [{ name: "Smør", quantity: 300, unit: "g" }, { name: "Mel", quantity: 300, unit: "g" }, { name: "Hønsefond", quantity: 4000, unit: "ml" }, { name: "Fløde", quantity: 2000, unit: "ml" }, { name: "Estragon, frisk", quantity: 200, unit: "g" }], method: ["Lav roux.", "Tilsæt fond og fløde.", "Tilsæt hakket estragon."] },
    "SC-024": { recipeName: "Spinatcreme", id: "SC-024", category: "Saucer", yield_net: "10.0 KG", ingredients: [{ name: "Spinat, blansjeret", quantity: 4000, unit: "g" }, { name: "Fløde", quantity: 4000, unit: "ml" }, { name: "Løg", quantity: 1000, unit: "g" }, { name: "Hvidløg", quantity: 100, unit: "g" }, { name: "Muskatnød", quantity: 10, unit: "g" }], method: ["Svits løg og hvidløg.", "Tilsæt spinat og fløde.", "Blend glat.", "Smag til med muskat."] },
    "SC-025": { recipeName: "Ratatouille", id: "SC-025", category: "Saucer", yield_net: "15.0 KG", ingredients: [{ name: "Squash", quantity: 3000, unit: "g" }, { name: "Aubergine", quantity: 3000, unit: "g" }, { name: "Peberfrugt", quantity: 3000, unit: "g" }, { name: "Tomater", quantity: 4000, unit: "g" }, { name: "Løg", quantity: 2000, unit: "g" }, { name: "Hvidløg", quantity: 100, unit: "g" }], method: ["Skær alle grøntsager i tern.", "Steg enkeltvis.", "Bland med tomater.", "Simrer 30 min."] },
    "SC-026": { recipeName: "Urtecreme", id: "SC-026", category: "Saucer", yield_net: "8.0 KG", ingredients: [{ name: "Cremefraiche", quantity: 5000, unit: "g" }, { name: "Dild", quantity: 200, unit: "g" }, { name: "Purløg", quantity: 150, unit: "g" }, { name: "Persille", quantity: 150, unit: "g" }, { name: "Citronsaft", quantity: 100, unit: "ml" }], method: ["Hak urter fint.", "Bland med cremefraiche.", "Smag til med citron."] },
};

// Export all in one object
export const allNewRecipes = {
    ...fiskeOpskrifter,
    ...hovedretterSprint2,
    ...saucerKomplet,
};
