// CaterCare Complete Recipe Database - Sprint 6+
// Resterende hovedretter, festmenuer og specialretter
// Genereret: 2026-01-12

// ===== FESTMENU & HELLIGDAGSRETTER =====
export const festOgHelligdage: Record<string, any> = {
    "FE-001": { recipeName: "Juleand", id: "FE-001", category: "Festmenu", yield_net: "20 STK", ingredients: [{ name: "Ænder, hele", quantity: 25000, unit: "g" }, { name: "Æbler", quantity: 3000, unit: "g" }, { name: "Svesker", quantity: 2000, unit: "g" }, { name: "Salt og peber", quantity: 200, unit: "g" }], method: ["Fyld ænder med æbler og svesker.", "Steg ved 170°C i 2-2.5 timer.", "Kernetemperatur: 75°C.", "Server med rødkål og brunede kartofler."] },
    "FE-002": { recipeName: "Flæskesteg m. svær", id: "FE-002", category: "Festmenu", yield_net: "35.0 KG", ingredients: [{ name: "Flæskesteg m. svær", quantity: 30000, unit: "g" }, { name: "Salt", quantity: 500, unit: "g" }, { name: "Laurbærblade", quantity: 30, unit: "g" }], method: ["Ridse svær i mønster.", "Gnid med salt.", "Steg ved 180°C.", "Afslut ved 220°C for sprød svær."] },
    "FE-003": { recipeName: "Ribbensteg", id: "FE-003", category: "Festmenu", yield_net: "30.0 KG", ingredients: [{ name: "Ribben, med svær", quantity: 28000, unit: "g" }, { name: "Salt", quantity: 400, unit: "g" }], method: ["Ridse svær.", "Steg langsomt først.", "Skru op til sidst.", "Server med brun sauce."] },
    "FE-004": { recipeName: "Kamsteg", id: "FE-004", category: "Festmenu", yield_net: "30.0 KG", ingredients: [{ name: "Kamsteg m. svær", quantity: 28000, unit: "g" }, { name: "Salt", quantity: 400, unit: "g" }, { name: "Hvidløg", quantity: 100, unit: "g" }], method: ["Gnid med salt og hvidløg.", "Steg ved 170°C i 3 timer.", "Sprød svær til sidst."] },
    "FE-005": { recipeName: "Lammekølle", id: "FE-005", category: "Festmenu", yield_net: "25.0 KG", ingredients: [{ name: "Lammekølle", quantity: 22000, unit: "g" }, { name: "Hvidløg", quantity: 200, unit: "g" }, { name: "Rosmarin", quantity: 100, unit: "g" }, { name: "Olivenolie", quantity: 300, unit: "ml" }], method: ["Spæk med hvidløg og rosmarin.", "Steg ved 160°C.", "Kernetemperatur: 60°C for medium.", "Hvil 20 min."] },
    "FE-006": { recipeName: "Lammesteg", id: "FE-006", category: "Festmenu", yield_net: "22.0 KG", ingredients: [{ name: "Lammekuller", quantity: 20000, unit: "g" }, { name: "Hvidløg og rosmarin", quantity: 300, unit: "g" }], method: ["Krydr og brun.", "Steg langsomt.", "Server med skysauce."] },
    "FE-007": { recipeName: "Andesteg", id: "FE-007", category: "Festmenu", yield_net: "25.0 KG", ingredients: [{ name: "Andebryst", quantity: 22000, unit: "g" }, { name: "Salt og peber", quantity: 150, unit: "g" }], method: ["Ridse skind.", "Steg skindside ned først.", "Færdig i ovn.", "Server med andesauce."] },
    "FE-008": { recipeName: "Andebryst", id: "FE-008", category: "Festmenu", yield_net: "20.0 KG", ingredients: [{ name: "Andebryst", quantity: 18000, unit: "g" }, { name: "Salt", quantity: 150, unit: "g" }], method: ["Steg skindside ned.", "Finish i ovn ved 180°C.", "Hvil og skær."] },
    "FE-009": { recipeName: "Wienerschnitzel", id: "FE-009", category: "Hovedretter", yield_net: "25.0 KG", ingredients: [{ name: "Kalveskiver", quantity: 20000, unit: "g" }, { name: "Mel", quantity: 1000, unit: "g" }, { name: "Æg", quantity: 1500, unit: "g" }, { name: "Rasp", quantity: 2000, unit: "g" }, { name: "Smør", quantity: 2000, unit: "g" }], method: ["Bank skiver ultra tynde.", "Vend i mel, æg, rasp.", "Steg i smør.", "Server med citron."] },
    "FE-010": { recipeName: "Oksemørbrad", id: "FE-010", category: "Festmenu", yield_net: "25.0 KG", ingredients: [{ name: "Oksemørbrad, hel", quantity: 22000, unit: "g" }, { name: "Smør", quantity: 1500, unit: "g" }], method: ["Brun på alle sider.", "Steg ved 130°C.", "Kernetemperatur: 54°C for medium rare.", "Hvil 15 min."] },
    "FE-011": { recipeName: "Julefrikadeller", id: "FE-011", category: "Festmenu", yield_net: "25.0 KG", ingredients: [{ name: "Svinefars", quantity: 15000, unit: "g" }, { name: "Kalvefars", quantity: 5000, unit: "g" }, { name: "Løg", quantity: 2000, unit: "g" }, { name: "Allehånde ekstra", quantity: 50, unit: "g" }], method: ["Bland fars med ekstra krydderier.", "Form små frikadeller.", "Steg sprøde."] },
    "FE-012": { recipeName: "Julemedister", id: "FE-012", category: "Festmenu", yield_net: "20.0 KG", ingredients: [{ name: "Medisterpølse", quantity: 20000, unit: "g" }], method: ["Steg langsomt i smør.", "Eller bag i ovn.", "Server med rødkål."] },
    "FE-013": { recipeName: "Fastelavnsboller", id: "FE-013", category: "Desserter", yield_net: "100 STK", ingredients: [{ name: "Gærdej", quantity: 4000, unit: "g" }, { name: "Smør", quantity: 1000, unit: "g" }, { name: "Flødeskum", quantity: 3000, unit: "ml" }, { name: "Glasur", quantity: 1500, unit: "g" }], method: ["Form runde boller.", "Hæv og bag.", "Fyld med flødeskum.", "Glasér."] },
    "FE-014": { recipeName: "Nytårskage", id: "FE-014", category: "Desserter", yield_net: "60 STK", ingredients: [{ name: "Lagkagebunde", quantity: 3000, unit: "g" }, { name: "Flødeskum", quantity: 4000, unit: "ml" }, { name: "Frugt", quantity: 2000, unit: "g" }, { name: "Marcipan", quantity: 1500, unit: "g" }], method: ["Lag af bund, fløde, frugt.", "Dekorer med marcipan.", "Pynt festligt."] },
    "FE-015": { recipeName: "Kongekage", id: "FE-015", category: "Desserter", yield_net: "60 STK", ingredients: [{ name: "Wienerbrødsdej", quantity: 4000, unit: "g" }, { name: "Remonce", quantity: 2000, unit: "g" }, { name: "Glasur", quantity: 1000, unit: "g" }], method: ["Rul dej med remonce.", "Form til krans.", "Bag og glasér."] },
    "FE-016": { recipeName: "Påskekage", id: "FE-016", category: "Desserter", yield_net: "60 STK", ingredients: [{ name: "Sukkerbrødsdej", quantity: 3000, unit: "g" }, { name: "Flødeskum", quantity: 3000, unit: "ml" }, { name: "Marcipanæg", quantity: 500, unit: "g" }], method: ["Bag lagkagebunde.", "Lag med fløde.", "Dekorer med marcipanæg."] },
};

// ===== RESTERENDE HOVEDRETTER (Kylling, Svin, Vegetar) =====
export const hovedretterSprint6: Record<string, any> = {
    "HO-036": { recipeName: "Kyllingebryst", id: "HO-036", category: "Fjerkræ", yield_net: "25.0 KG", ingredients: [{ name: "Kyllingebryst", quantity: 22000, unit: "g" }, { name: "Smør", quantity: 1500, unit: "g" }, { name: "Salt og peber", quantity: 150, unit: "g" }], method: ["Krydr bryst.", "Steg ved middel varme.", "Kernetemperatur: 72°C."] },
    "HO-037": { recipeName: "Kyllingedeller", id: "HO-037", category: "Fjerkræ", yield_net: "25.0 KG", ingredients: [{ name: "Kyllingefars", quantity: 18000, unit: "g" }, { name: "Løg", quantity: 2000, unit: "g" }, { name: "Æg", quantity: 800, unit: "g" }], method: ["Bland fars med løg og æg.", "Form til frikadeller.", "Steg eller bag."] },
    "HO-038": { recipeName: "Kyllingeboller i karry", id: "HO-038", category: "Fjerkræ", yield_net: "40.0 KG", ingredients: [{ name: "Kyllingefars", quantity: 15000, unit: "g" }, { name: "Karrysauce (SC-002)", quantity: 20000, unit: "g" }], method: ["Form fars til boller.", "Steg eller pocher.", "Læg i karrysauce."] },
    "HO-039": { recipeName: "Kyllingefrikassé", id: "HO-039", category: "Fjerkræ", yield_net: "45.0 KG", ingredients: [{ name: "Kylling i tern", quantity: 18000, unit: "g" }, { name: "Frikassésauce (SC-010)", quantity: 22000, unit: "g" }], method: ["Kog eller steg kylling.", "Tilsæt frikassésauce.", "Server med kartofler."] },
    "HO-040": { recipeName: "Kylling i Peberrod", id: "HO-040", category: "Fjerkræ", yield_net: "45.0 KG", ingredients: [{ name: "Kylling i tern", quantity: 18000, unit: "g" }, { name: "Peberrodssauce (SC-003)", quantity: 20000, unit: "g" }], method: ["Kog kylling.", "Bland med peberrodssauce."] },
    "HO-041": { recipeName: "Kylling i Paprika", id: "HO-041", category: "Fjerkræ", yield_net: "45.0 KG", ingredients: [{ name: "Kylling i tern", quantity: 18000, unit: "g" }, { name: "Paprikasauce (SC-007)", quantity: 20000, unit: "g" }], method: ["Brun kylling.", "Tilsæt paprikasauce."] },
    "HO-042": { recipeName: "Chicken Tikka Masala", id: "HO-042", category: "Fjerkræ", yield_net: "45.0 KG", ingredients: [{ name: "Kyllingebryst, i tern", quantity: 18000, unit: "g" }, { name: "Yoghurt marinade", quantity: 3000, unit: "g" }, { name: "Tikka sauce", quantity: 18000, unit: "g" }], method: ["Mariner kylling.", "Grill eller steg.", "Tilsæt tikka sauce."] },
    "HO-043": { recipeName: "Glaseret Skinke", id: "HO-043", category: "Svinekød", yield_net: "25.0 KG", ingredients: [{ name: "Skinke, kogt", quantity: 22000, unit: "g" }, { name: "Honning", quantity: 500, unit: "g" }, { name: "Sennep", quantity: 300, unit: "g" }, { name: "Nelliker", quantity: 30, unit: "g" }], method: ["Bland glasur.", "Pensl skinke.", "Bag ved 180°C.", "Genglasér flere gange."] },
    "HO-044": { recipeName: "Skinke m. flødekartofler", id: "HO-044", category: "Svinekød", yield_net: "40.0 KG", ingredients: [{ name: "Skinkeskiver", quantity: 18000, unit: "g" }, { name: "Flødekartofler (KH-002)", quantity: 22000, unit: "g" }], method: ["Opvarm skinke.", "Server med flødekartofler og bønner."] },
    "HO-045": { recipeName: "Hjerter i fløde", id: "HO-045", category: "Svinekød", yield_net: "35.0 KG", ingredients: [{ name: "Svinehjerter", quantity: 18000, unit: "g" }, { name: "Løg", quantity: 3000, unit: "g" }, { name: "Fløde", quantity: 5000, unit: "ml" }, { name: "Fond", quantity: 5000, unit: "ml" }], method: ["Rens og skær hjerter.", "Brun og tilsæt løg.", "Tilsæt fond.", "Simrer til møre.", "Tilsæt fløde."] },
    "HO-046": { recipeName: "Farseret Porre", id: "HO-046", category: "Svinekød", yield_net: "50 STK", ingredients: [{ name: "Porrer, store", quantity: 8000, unit: "g" }, { name: "Svinefars", quantity: 10000, unit: "g" }, { name: "Skysauce", quantity: 8000, unit: "g" }], method: ["Blanchér porrer.", "Fyld med fars.", "Bag i sauce."] },
    "HO-047": { recipeName: "Mørbrad i fad", id: "HO-047", category: "Svinekød", yield_net: "40.0 KG", ingredients: [{ name: "Svinemørbrad", quantity: 18000, unit: "g" }, { name: "Kartofler", quantity: 12000, unit: "g" }, { name: "Paprikasauce", quantity: 10000, unit: "g" }], method: ["Brun mørbrad.", "Læg i fad med kartofler.", "Hæld sauce over.", "Bag 40 min."] },
    "HO-048": { recipeName: "Pølse m. krydderurt", id: "HO-048", category: "Svinekød", yield_net: "20.0 KG", ingredients: [{ name: "Krydderurtspølser", quantity: 20000, unit: "g" }], method: ["Steg eller kog pølser.", "Server med løgsovs."] },
    "HO-049": { recipeName: "Vegetarisk Postej", id: "HO-049", category: "Vegetar", yield_net: "15.0 KG", ingredients: [{ name: "Linser, kogte", quantity: 5000, unit: "g" }, { name: "Grøntsager, blendet", quantity: 4000, unit: "g" }, { name: "Løg", quantity: 2000, unit: "g" }, { name: "Æg", quantity: 1000, unit: "g" }, { name: "Krydderier", quantity: 200, unit: "g" }], method: ["Blend linser og grøntsager.", "Tilsæt æg og krydderier.", "Bag ved 175°C i 45 min."] },
    "HO-050": { recipeName: "Chili sin carne", id: "HO-050", category: "Vegetar", yield_net: "40.0 KG", ingredients: [{ name: "Bønner, blandede", quantity: 10000, unit: "g" }, { name: "Tomater, hakkede", quantity: 10000, unit: "g" }, { name: "Løg", quantity: 4000, unit: "g" }, { name: "Peberfrugt", quantity: 4000, unit: "g" }, { name: "Chilipulver", quantity: 150, unit: "g" }], method: ["Svits løg og peberfrugt.", "Tilsæt tomater og bønner.", "Krydr og simrer 30 min."] },
    "HO-051": { recipeName: "Pastinakpostej", id: "HO-051", category: "Vegetar", yield_net: "20.0 KG", ingredients: [{ name: "Pastinak", quantity: 10000, unit: "g" }, { name: "Æg", quantity: 1500, unit: "g" }, { name: "Fløde", quantity: 3000, unit: "ml" }, { name: "Ost", quantity: 2000, unit: "g" }], method: ["Kog og mos pastinak.", "Bland med æg og fløde.", "Bag til sat."] },
    "HO-052": { recipeName: "Pennepasta m. svampesovs", id: "HO-052", category: "Vegetar", yield_net: "35.0 KG", ingredients: [{ name: "Penne pasta", quantity: 12000, unit: "g" }, { name: "Svampesovs (SC-022)", quantity: 15000, unit: "g" }], method: ["Kog pasta.", "Bland med svampesovs."] },
    "HO-053": { recipeName: "Gule Ærter", id: "HO-053", category: "Sammenkogte", yield_net: "50.0 KG", ingredients: [{ name: "Gule ærter, tørre", quantity: 8000, unit: "g" }, { name: "Flæsk, saltet", quantity: 10000, unit: "g" }, { name: "Løg", quantity: 4000, unit: "g" }, { name: "Gulerødder", quantity: 4000, unit: "g" }, { name: "Porre", quantity: 3000, unit: "g" }], method: ["Læg ærter i blød.", "Kog med flæsk og grøntsager.", "Simrer til ærter er møre.", "Server med sennep."] },
    "HO-054": { recipeName: "Sommertærte", id: "HO-054", category: "Vegetar", yield_net: "50 STK", ingredients: [{ name: "Tærtedeig", quantity: 5000, unit: "g" }, { name: "Sommergrøntsager", quantity: 8000, unit: "g" }, { name: "Æg", quantity: 2000, unit: "g" }, { name: "Fløde", quantity: 3000, unit: "ml" }], method: ["Beklæd forme.", "Fyld med grøntsager.", "Hæld æggemasse over.", "Bag."] },
    "HO-055": { recipeName: "Grøntsagstærte", id: "HO-055", category: "Vegetar", yield_net: "50 STK", ingredients: [{ name: "Tærtedeig", quantity: 5000, unit: "g" }, { name: "Grøntsagsblanding", quantity: 8000, unit: "g" }, { name: "Cremefraiche", quantity: 3000, unit: "g" }, { name: "Æg", quantity: 1500, unit: "g" }], method: ["Beklæd forme.", "Fyld med grøntsager.", "Hæld æggemix over.", "Bag."] },
    "HO-056": { recipeName: "Gulerodsgratin", id: "HO-056", category: "Vegetar", yield_net: "20.0 KG", ingredients: [{ name: "Gulerødder", quantity: 15000, unit: "g" }, { name: "Bechamel", quantity: 6000, unit: "g" }, { name: "Ost", quantity: 2000, unit: "g" }], method: ["Kog gulerødder halvmøre.", "Læg i fade med bechamel.", "Top med ost.", "Gratiner."] },
    "HO-057": { recipeName: "Sommergryde (Veg)", id: "HO-057", category: "Vegetar", yield_net: "40.0 KG", ingredients: [{ name: "Squash", quantity: 5000, unit: "g" }, { name: "Peberfrugt", quantity: 5000, unit: "g" }, { name: "Tomater", quantity: 8000, unit: "g" }, { name: "Bønner", quantity: 4000, unit: "g" }, { name: "Linser", quantity: 4000, unit: "g" }], method: ["Svits grøntsager.", "Tilsæt bønner og linser.", "Simrer med tomatflødesauce."] },
    "HO-058": { recipeName: "Spansk æggekage", id: "HO-058", category: "Vegetar", yield_net: "25.0 KG", ingredients: [{ name: "Æg", quantity: 5000, unit: "g" }, { name: "Kartofler, kogte i tern", quantity: 8000, unit: "g" }, { name: "Løg", quantity: 2000, unit: "g" }, { name: "Peberfrugt", quantity: 2000, unit: "g" }], method: ["Steg kartofler og grøntsager.", "Hæld pisket æg over.", "Steg til sat.", "Vend på tallerken."] },
};

// ===== RESTERENDE DESSERTER, SUPPER OG TILBEHØR =====
export const resterendeKomponenter: Record<string, any> = {
    // Flere desserter
    "DS-036": { recipeName: "Rubinsteinerkage", id: "DS-036", category: "Kager", yield_net: "60 STK", ingredients: [{ name: "Chokoladekage", quantity: 3000, unit: "g" }, { name: "Flødeskum", quantity: 3000, unit: "ml" }, { name: "Hindbær", quantity: 1500, unit: "g" }], method: ["Bag chokoladebunde.", "Lag med fløde og hindbær."] },
    "DS-037": { recipeName: "Krydderkage", id: "DS-037", category: "Kager", yield_net: "60 STK", ingredients: [{ name: "Mel", quantity: 1000, unit: "g" }, { name: "Sirup", quantity: 800, unit: "g" }, { name: "Krydderier", quantity: 50, unit: "g" }], method: ["Bland ingredienser.", "Bag ved 175°C."] },
    "DS-038": { recipeName: "Cremelinser", id: "DS-038", category: "Desserter", yield_net: "100 STK", ingredients: [{ name: "Mørdej", quantity: 2000, unit: "g" }, { name: "Vanillecreme", quantity: 3000, unit: "g" }, { name: "Glasur", quantity: 1000, unit: "g" }], method: ["Bag tærteletter.", "Fyld med creme.", "Glasér."] },
    "DS-039": { recipeName: "Kokostoppe", id: "DS-039", category: "Småkager", yield_net: "100 STK", ingredients: [{ name: "Kokos", quantity: 1500, unit: "g" }, { name: "Sukker", quantity: 800, unit: "g" }, { name: "Æggehvider", quantity: 500, unit: "g" }], method: ["Bland ingredienser.", "Form toppe.", "Bag ved 180°C."] },
    "DS-040": { recipeName: "Hindbærstrifli", id: "DS-040", category: "Desserter", yield_net: "15.0 KG", ingredients: [{ name: "Hindbær", quantity: 5000, unit: "g" }, { name: "Vaniljepudding", quantity: 5000, unit: "g" }, { name: "Flødeskum", quantity: 3000, unit: "ml" }], method: ["Lag af hindbær, pudding og fløde.", "Køl."] },
    "DS-041": { recipeName: "Fløderand m. frugt", id: "DS-041", category: "Desserter", yield_net: "12.0 KG", ingredients: [{ name: "Fløde", quantity: 6000, unit: "ml" }, { name: "Husblas", quantity: 80, unit: "g" }, { name: "Sukker", quantity: 600, unit: "g" }, { name: "Frugt", quantity: 3000, unit: "g" }], method: ["Lav flødeskum med husblas.", "Hæld i randform.", "Server med frugt."] },
    "DS-042": { recipeName: "Æblekompot", id: "DS-042", category: "Desserter", yield_net: "15.0 KG", ingredients: [{ name: "Æbler", quantity: 12000, unit: "g" }, { name: "Sukker", quantity: 2000, unit: "g" }, { name: "Vanilje", quantity: 20, unit: "g" }], method: ["Kog æbler.", "Tilsæt sukker og vanilje.", "Mos let."] },
    // Flere supper
    "SU-008": { recipeName: "Gulerodssuppe", id: "SU-008", category: "Supper", yield_net: "50.0 KG", ingredients: [{ name: "Gulerødder", quantity: 25000, unit: "g" }, { name: "Løg", quantity: 5000, unit: "g" }, { name: "Ingefær", quantity: 200, unit: "g" }, { name: "Fond", quantity: 15000, unit: "ml" }, { name: "Fløde", quantity: 5000, unit: "ml" }], method: ["Svits løg.", "Tilsæt gulerødder og fond.", "Kog mørt.", "Blend og tilsæt fløde."] },
    "SU-009": { recipeName: "Græskarsuppe", id: "SU-009", category: "Supper", yield_net: "50.0 KG", ingredients: [{ name: "Græskar", quantity: 25000, unit: "g" }, { name: "Løg", quantity: 4000, unit: "g" }, { name: "Fond", quantity: 15000, unit: "ml" }, { name: "Fløde", quantity: 5000, unit: "ml" }], method: ["Bag græskar.", "Blend med fond.", "Tilsæt fløde."] },
    "SU-010": { recipeName: "Hyldebærsuppe", id: "SU-010", category: "Supper", yield_net: "25.0 KG", ingredients: [{ name: "Hyldebær saft", quantity: 15000, unit: "ml" }, { name: "Æbler, i tern", quantity: 5000, unit: "g" }, { name: "Sukker", quantity: 2000, unit: "g" }], method: ["Kog saft og æbler.", "Tilsæt sukker.", "Jævn."] },
    // Flere tilbehør
    "TB-016": { recipeName: "Gulerodssalat", id: "TB-016", category: "Tilbehør", yield_net: "10.0 KG", ingredients: [{ name: "Gulerødder, revet", quantity: 8000, unit: "g" }, { name: "Appelsin", quantity: 1000, unit: "g" }, { name: "Rosiner", quantity: 500, unit: "g" }], method: ["Riv gulerødder.", "Bland med appelsin og rosiner."] },
    "TB-017": { recipeName: "Spinatsalat", id: "TB-017", category: "Tilbehør", yield_net: "8.0 KG", ingredients: [{ name: "Babyspinat", quantity: 6000, unit: "g" }, { name: "Valnødder", quantity: 500, unit: "g" }, { name: "Vinaigrette", quantity: 1500, unit: "ml" }], method: ["Vask spinat.", "Bland med nødder og dressing."] },
    "TB-018": { recipeName: "Bagte grøntsager", id: "TB-018", category: "Tilbehør", yield_net: "15.0 KG", ingredients: [{ name: "Grøntsagsblanding", quantity: 14000, unit: "g" }, { name: "Olivenolie", quantity: 500, unit: "ml" }, { name: "Krydderurter", quantity: 100, unit: "g" }], method: ["Skær grøntsager.", "Vend i olie og krydderier.", "Bag ved 200°C."] },
    "TB-019": { recipeName: "Ribsgelé", id: "TB-019", category: "Tilbehør", yield_net: "5.0 KG", ingredients: [{ name: "Ribs", quantity: 3000, unit: "g" }, { name: "Sukker", quantity: 2000, unit: "g" }, { name: "Pektin", quantity: 50, unit: "g" }], method: ["Kog ribs.", "Tilsæt sukker og pektin.", "Hæld på glas."] },
    "TB-020": { recipeName: "Tyttebær", id: "TB-020", category: "Tilbehør", yield_net: "5.0 KG", ingredients: [{ name: "Tyttebær", quantity: 3000, unit: "g" }, { name: "Sukker", quantity: 2000, unit: "g" }], method: ["Kog tyttebær med sukker.", "Afkøl."] },
    "TB-021": { recipeName: "Syltet agurk", id: "TB-021", category: "Tilbehør", yield_net: "10.0 KG", ingredients: [{ name: "Agurker", quantity: 8000, unit: "g" }, { name: "Eddike", quantity: 1000, unit: "ml" }, { name: "Sukker", quantity: 1000, unit: "g" }], method: ["Skær agurker.", "Lav lage.", "Læg agurker i lage."] },
    "TB-022": { recipeName: "Syltet rødløg", id: "TB-022", category: "Tilbehør", yield_net: "8.0 KG", ingredients: [{ name: "Rødløg", quantity: 6000, unit: "g" }, { name: "Eddike", quantity: 1000, unit: "ml" }, { name: "Sukker", quantity: 1000, unit: "g" }], method: ["Skær løg i ringe.", "Kog lage.", "Hæld over løg."] },
    "TB-023": { recipeName: "Stuvede kål", id: "TB-023", category: "Tilbehør", yield_net: "12.0 KG", ingredients: [{ name: "Hvidkål", quantity: 10000, unit: "g" }, { name: "Smør", quantity: 500, unit: "g" }, { name: "Mel", quantity: 300, unit: "g" }, { name: "Mælk", quantity: 3000, unit: "ml" }], method: ["Snit kål.", "Lav hvid sauce.", "Bland kål i sauce."] },
    "TB-024": { recipeName: "Dampede gulerødder", id: "TB-024", category: "Tilbehør", yield_net: "10.0 KG", ingredients: [{ name: "Gulerødder", quantity: 10000, unit: "g" }, { name: "Smør", quantity: 300, unit: "g" }], method: ["Skær gulerødder.", "Damp til møre.", "Vend i smør."] },
    "TB-025": { recipeName: "Perleløg (glaseret)", id: "TB-025", category: "Tilbehør", yield_net: "8.0 KG", ingredients: [{ name: "Perleløg", quantity: 6000, unit: "g" }, { name: "Smør", quantity: 500, unit: "g" }, { name: "Sukker", quantity: 300, unit: "g" }], method: ["Skræl løg.", "Glasér i smør og sukker."] },
};

// Export Sprint 6+
export const allSprint6Recipes = {
    ...festOgHelligdage,
    ...hovedretterSprint6,
    ...resterendeKomponenter,
};
