export const february2026 = [
    { date: "1. feb (Søn)", icon: "🐂", type: "Okse", dish: "Gl.dags Oksesteg", protein: "90g", sauce: "Peberrodssauce", carb: "Kartofler", veg: "Bønner", biret: "Citronfromage (90g)", isHoliday: true },
    { date: "2. feb (Man)", icon: "🐖", type: "Gris", dish: "Mørbradgryde", protein: "180g", sauce: "Paprikasauce", carb: "Ris", veg: "Cocktailpølser", biret: "Minestronesuppe (150g)" },
    { date: "3. feb (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Karry", protein: "180g", sauce: "Karrysauce", carb: "Løse Ris", veg: "Mango chutney", biret: "Chokoladekage (70g)" },
    { date: "4. feb (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred", protein: "90g", sauce: "Sennepsauce", carb: "Kartofler", veg: "Rødbedetern", biret: "Rabarbertrifli (90g)" },
    { date: "5. feb (Tor)", icon: "🥦", type: "Grøn", dish: "Grøntsagslasagne", protein: "200g", sauce: "Tomat/Bechamel", carb: "(Pasta i ret)", veg: "Tomatsalat", biret: "Kartoffel-porresuppe (150g)" },
    { date: "6. feb (Fre)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2stk/90g", sauce: "Brun sauce", carb: "Kartofler", veg: "Surkål", biret: "Drømmekage (70g)" },
    { date: "7. feb (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g", sauce: "Aspargessauce", carb: "Tarteletter (2stk)", veg: "Persille/Tomat", biret: "Frugtsalat m. creme (100g)" },
    { date: "8. feb (Søn)", icon: "🐂", type: "Okse", dish: "Kalvesteg", protein: "90g", sauce: "Vildtsauce", carb: "Kartofler", veg: "Waldorfsalat", biret: "Karamelrand (90g)", isHoliday: true },
    { date: "9. feb (Man)", icon: "🐖", type: "Gris", dish: "Brændende Kærlighed", protein: "200g", sauce: "(Fedtstof i mos)", carb: "Kartoffelmos", veg: "Bacon/Løg", biret: "Tomatsuppe (150g)" },
    { date: "10. feb (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Unghanebryst", protein: "90g", sauce: "Skysauce", carb: "Kartofler", veg: "Agurkesalat", biret: "Gulerodskage (70g)" },
    { date: "11. feb (Ons)", icon: "🥦", type: "Grøn", dish: "Porretærte", protein: "150g", sauce: "Cremefraiche", carb: "-", veg: "Tomatsalat", biret: "Aspargessuppe (150g)" },
    { date: "12. feb (Tor)", icon: "🐟", type: "Fisk", dish: "Ovnbagt Ørred", protein: "90g", sauce: "Citronsauce", carb: "Kartofler", veg: "Spinat", biret: "Romfromage (90g)" },
    { date: "13. feb (Fre)", icon: "🐖", type: "Gris", dish: "Skinke m. flødekart.", protein: "90g", sauce: "(Fløde i kart.)", carb: "Flødekartofler", veg: "Grønne bønner", biret: "Banankage (70g)" },
    { date: "14. feb (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingeboller i karry", protein: "90g", sauce: "Karrysauce", carb: "Ris", veg: "Chutney", biret: "Sveskegrød m. fløde (150g)" },
    { date: "15. feb (Søn) 🎭", icon: "🐖", type: "Gris", dish: "Fastelavn: Bankekød", protein: "90g", sauce: "Brun sauce", carb: "Kartoffelmos", veg: "Laurbærblade", biret: "Fastelavnsbolle (1 stk)", isHoliday: true },
    { date: "16. feb (Man)", icon: "🐖", type: "Gris", dish: "Svensk Pølseret", protein: "200g", sauce: "Tomat/Fløde", carb: "Kartofler", veg: "Purløg", biret: "Blomkålssuppe (150g)" },
    { date: "17. feb (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingefrikassé", protein: "180g", sauce: "Frikassésauce", carb: "Kartofler", veg: "Ærter/Gulerød.", biret: "Citronmåne (70g)" },
    { date: "18. feb (Ons)", icon: "🐟", type: "Fisk", dish: "Fiskefrikadeller", protein: "2stk/90g", sauce: "Remoulade", carb: "Kartofler", veg: "Citron", biret: "Budding m. saft (100g)" },
    { date: "19. feb (Tor)", icon: "🥦", type: "Grøn", dish: "Blomkålsgratin", protein: "160g", sauce: "Smeltet smør", carb: "Rugbrød (1sk)", veg: "Gulerodssalat", biret: "Klar suppe m. boller (150g)" },
    { date: "20. feb (Fre)", icon: "🐖", type: "Gris", dish: "Karbonader", protein: "1stk/110g", sauce: "Stuvede ærter", carb: "Kartofler", veg: "Gulerødder", biret: "Sandkage (70g)" },
    { date: "21. feb (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Paprikagryde (Kyl)", protein: "180g", sauce: "Paprikasauce", carb: "Ris", veg: "Persille", biret: "Jordbærgrød m. fløde (150g)" },
    { date: "22. feb (Søn)", icon: "🐂", type: "Okse", dish: "Benløse Fugle", protein: "2stk/90g", sauce: "Skysauce", carb: "Kartoffelmos", veg: "Tyttebær", biret: "Sherryfromage (90g)", isHoliday: true },
    { date: "23. feb (Man)", icon: "🐖", type: "Gris", dish: "Boller i Selleri", protein: "3stk/90g", sauce: "Sellerisauce", carb: "Kartofler", veg: "Persille", biret: "Minestronesuppe (150g)" },
    { date: "24. feb (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Sprængt Kylling", protein: "90g", sauce: "Peberrodssauce", carb: "Kartofler", veg: "Gulerødder", biret: "Kage m. creme (70g)" },
    { date: "25. feb (Ons)", icon: "🥦", type: "Grøn", dish: "Ovnæggekage", protein: "150g", sauce: "-", carb: "Rugbrød (1sk)", veg: "Tomat/Purløg", biret: "Grøntsagssuppe (150g)" },
    { date: "26. feb (Tor)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g", sauce: "Persillesauce", carb: "Kartofler", veg: "Citron", biret: "Fersken m. fløde (100g)" },
    { date: "27. feb (Fre)", icon: "🐖", type: "Gris", dish: "Forloren Hare", protein: "90g", sauce: "Vildtsauce", carb: "Kartofler", veg: "Ribsgelé", biret: "Hindbærsnitte (60g)" },
    { date: "28. feb (Lør)", icon: "🐂", type: "Okse", dish: "Hakkebøf", protein: "90g", sauce: "Brun sauce", carb: "Kartofler", veg: "Bløde løg", biret: "Pæretærte (90g)" },
];
