export const january2026 = [
    { date: "1. jan (Tor)", icon: "🐂", type: "Okse", dish: "Lasagne m. kødsauce", protein: "90g Kød", sauce: "Tomat/Bechamel", carb: "Brød (1 stk)", veg: "Råkost", biret: "Fløderand m. frugt (90g)", isHoliday: true },
    { date: "2. jan (Fre)", icon: "🥦", type: "Grøn", dish: "Chili sin carne", protein: "Vegetar/Bønner", sauce: "Tomatsauce", carb: "Ris", veg: "Creme fraiche", biret: "Ost og Sprød (60g)" },
    { date: "3. jan (Lør)", icon: "🐓", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g", sauce: "Aspargessauce", carb: "Tarteletter (2 stk)", veg: "Tomat/Persille", biret: "Chokoladekage (70g)" },
    { date: "4. jan (Søn)", icon: "🐂", type: "Okse", dish: "Gl.dags Rullesteg", protein: "90g", sauce: "Skysauce", carb: "Kartofler", veg: "Rødbeder", biret: "Rødgrød m. fløde (150g)", isHoliday: true },
    { date: "5. jan (Man)", icon: "🐖", type: "Gris", dish: "Skipperlabskovs", protein: "250g", sauce: "(I retten)", carb: "Rugbrød (1 sk)", veg: "Rødbeder", biret: "Gulerodssuppe (150g)" },
    { date: "6. jan (Tir)", icon: "🐓", type: "Fjerkræ", dish: "Sprængt kylling", protein: "90g", sauce: "Flødesauce", carb: "Kartofler", veg: "Rabarberkompot", biret: "Æblekompot m. skum (90g)" },
    { date: "7. jan (Ons)", icon: "🐟", type: "Fisk", dish: "Bagte ørred", protein: "90g", sauce: "Spinatcreme", carb: "Kartofler", veg: "Rødløg", biret: "Pannacotta (90g)" },
    { date: "8. jan (Tor)", icon: "🥦", type: "Grøn", dish: "Pastinakpostej", protein: "110g", sauce: "Ratatouille", carb: "Kartofler", veg: "Sylt. agurker", biret: "Græskarsuppe (150g)" },
    { date: "9. jan (Fre)", icon: "🐖", type: "Gris", dish: "Pølse m. krydderurt", protein: "110g", sauce: "Løgsovs", carb: "Kartoffelmos", veg: "Ærter", biret: "Drømmekage (70g)" },
    { date: "10. jan (Lør)", icon: "🐓", type: "Fjerkræ", dish: "Paprikagryde", protein: "180g", sauce: "Paprikasauce", carb: "Ris", veg: "Persille", biret: "Frugtsalat m. creme (100g)" },
    { date: "11. jan (Søn)", icon: "🐂", type: "Okse", dish: "Oksesteg", protein: "90g", sauce: "Portvinssauce", carb: "Flødekartofler", veg: "Ærter", biret: "Gulerodskage (70g)", isHoliday: true },
    { date: "12. jan (Man)", icon: "🐖", type: "Gris", dish: "Boller i karry", protein: "3stk/90g", sauce: "Karrysauce", carb: "Ris", veg: "Rabarberchutney", biret: "Ost m. knækbrød (60g)" },
    { date: "13. jan (Tir)", icon: "🐟", type: "Fisk", dish: "Paneret fisk", protein: "90g", sauce: "Remoulade", carb: "Stegte kart.", veg: "Citron", biret: "Jordbærgrød m. fløde (150g)" },
    { date: "14. jan (Ons) 👑", icon: "🐖", type: "Gris", dish: "Kongens Livret: Stegt flæsk", protein: "90g", sauce: "Persillesauce", carb: "Kartofler", veg: "Rødbeder", biret: "Kongekage (70g)", isHoliday: true },
    { date: "15. jan (Tor)", icon: "🥦", type: "Grøn", dish: "Pennepasta", protein: "Vegetar", sauce: "Svampesovs", carb: "Pasta", veg: "Løgdrys", biret: "Tomatsuppe (150g)" },
    { date: "16. jan (Fre)", icon: "🐖", type: "Gris", dish: "Hjerter i fløde", protein: "150g", sauce: "Flødesauce", carb: "Kartoffelmos", veg: "Spinatsalat", biret: "Sandkage (70g)" },
    { date: "17. jan (Lør)", icon: "🐓", type: "Fjerkræ", dish: "BBQ Kylling", protein: "90g", sauce: "BBQ sauce", carb: "Kartofler", veg: "Spidskål", biret: "Hindbærstrifli (90g)" },
    { date: "18. jan (Søn)", icon: "🐂", type: "Okse", dish: "Nakkesteg", protein: "90g", sauce: "Estragonsauce", carb: "Kartoffelmos", veg: "Bagte grønt", biret: "Henkogt frugt (90g)", isHoliday: true },
    { date: "19. jan (Man)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "2 stk/90g", sauce: "Stuvede kål", carb: "Kartofler", veg: "Syl. Rødløg", biret: "Cremet gulerodssuppe" },
    { date: "20. jan (Tir)", icon: "🐓", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g", sauce: "Cremet sauce", carb: "Ris", veg: "Broccoli", biret: "Cremelinser (70g)" },
    { date: "21. jan (Ons)", icon: "🐟", type: "Fisk", dish: "Fisk i sellerisalat", protein: "180g", sauce: "Sennepsauce", carb: "Kartofler", veg: "Citron", biret: "Budding m. saft (110g)" },
    { date: "22. jan (Tor)", icon: "🥦", type: "Grøn", dish: "Porretærte", protein: "160g", sauce: "Chili dressing", carb: "-", veg: "Tomatsalat", biret: "Minestrone (150g)" },
    { date: "23. jan (Fre)", icon: "🐖", type: "Gris", dish: "Forloren hare", protein: "90g", sauce: "Vildtsauce", carb: "Kartofler", veg: "Valnøddesalat", biret: "Kokostoppe (60g)" },
    { date: "24. jan (Lør)", icon: "🐓", type: "Fjerkræ", dish: "Høns i asparges", protein: "110g", sauce: "Aspargessauce", carb: "Tarteletter", veg: "Tomatsalat", biret: "Æblegrød (150g)" },
    { date: "25. jan (Søn)", icon: "🐂", type: "Okse", dish: "Oksesteg", protein: "90g", sauce: "Rødvinssauce", carb: "Flødekartofler", veg: "Gulerødder", biret: "Tiramisu (75g)", isHoliday: true },
    { date: "26. jan (Man)", icon: "🐖", type: "Gris", dish: "Krebinet", protein: "1 stk/110g", sauce: "Stuvning", carb: "Kartofler", veg: "Persille", biret: "Hyldebærsuppe m. æbler" },
    { date: "27. jan (Tir)", icon: "🐓", type: "Fjerkræ", dish: "Chicken Tikka", protein: "180g", sauce: "Masalasauce", carb: "Ris", veg: "Tzatziki", biret: "Frugtsalat (110g)" },
    { date: "28. jan (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt fisk", protein: "90g", sauce: "Hvidvinssauce", carb: "Kartofler", veg: "Grøntsager", biret: "Panna cotta m. passion" },
    { date: "29. jan (Tor)", icon: "🥦", type: "Grøn", dish: "Gulerodsgratin", protein: "160g", sauce: "Smør", carb: "Rugbrød", veg: "Tomater", biret: "Blomkålssuppe (150g)" },
    { date: "30. jan (Fre)", icon: "🐖", type: "Gris", dish: "Frikassé", protein: "180g", sauce: "Frikassésauce", carb: "Kartofler", veg: "Ærter", biret: "Gl.dags æblekage (90g)" },
    { date: "31. jan (Lør)", icon: "🐓", type: "Fjerkræ", dish: "Spansk æggekage", protein: "150g", sauce: "-", carb: "Rugbrød", veg: "Grønsalat", biret: "Citronfromage (90g)" },
];
