export const march2026 = [
    { date: "1. mar (Søn)", icon: "🐂", type: "Okse", dish: "Bankekød", protein: "80g Kød", sauce: "Sky (100g)", carb: "Mos (125g + 25g fløde)", veg: "Laurbær (35g)", biret: "Frugtgrød (125g + 25g fløde)", isHoliday: true },
    { date: "2. mar (Man)", icon: "🐖", type: "Gris", dish: "Grisefrikassé", protein: "180g Ret", sauce: "Frikassé (100g)", carb: "Kartofler (100g)", veg: "Ærter (50g)", biret: "Appelsinsuppe (200g)" },
    { date: "3. mar (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Karry", protein: "80g Kød", sauce: "Karry (100g)", carb: "Ris (100g)", veg: "Chutney (25g)", biret: "Krydderkage (70g)" },
    { date: "4. mar (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred (Vejle)", protein: "90g Fisk", sauce: "Urtecreme (80g)", carb: "Kartofler (100g)", veg: "Dild (35g)", biret: "Pæretærte (90g)" },
    { date: "5. mar (Tor)", icon: "🥦", type: "Grøn", dish: "Gule Ærter", protein: "Flæsk", sauce: "-", carb: "-", veg: "Sennep (25g)", biret: "Pandekager (2 stk)" },
    { date: "6. mar (Fre)", icon: "🐖", type: "Gris", dish: "Mørbradbøf", protein: "80g Kød", sauce: "Champignon (100g)", carb: "Kartofler (100g)", veg: "Løg (35g)", biret: "Sandkage (70g)" },
    { date: "7. mar (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g Ret", sauce: "Fløde (100g)", carb: "Kartofler (100g)", veg: "Gulerødder (50g)", biret: "Risengrød (250g)" },
    { date: "8. mar (Søn)", icon: "🐂", type: "Okse", dish: "Kalvegryde i flødesauce", protein: "180g Ret", sauce: "Fløde (100g)", carb: "Kartofler (100g)", veg: "Gulerødder (50g)", biret: "Rubinsteinerkage (70g)", isHoliday: true },
    { date: "9. mar (Man)", icon: "🐖", type: "Gris", dish: "Koteletter i fad", protein: "80g Kød", sauce: "Tomat/Fløde (100g)", carb: "Ris (100g)", veg: "-", biret: "Karrysuppe (200g)" },
    { date: "10. mar (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kalkungryde", protein: "180g Ret", sauce: "Fløde (100g)", carb: "Mos (125g + 25g fløde)", veg: "Gulerødder (50g)", biret: "Gulerodskage (70g)" },
    { date: "11. mar (Ons)", icon: "🐟", type: "Fisk", dish: "Bagt Ørred (Vejle)", protein: "90g Fisk", sauce: "Mandel (80g)", carb: "Kartofler (100g)", veg: "Grønt (50g)", biret: "Frugtsalat (100g)" },
    { date: "12. mar (Tor)", icon: "🥦", type: "Grøn", dish: "Spinattærte", protein: "150g Ret", sauce: "-", carb: "-", veg: "Tomatsalat (30g)", biret: "Kartoffel-porresuppe (200g)" },
    { date: "13. mar (Fre)", icon: "🐖", type: "Gris", dish: "Stegt Flæsk", protein: "80g Kød", sauce: "Persille (100g)", carb: "Kartofler (100g)", veg: "Rødbeder (50g)", biret: "Æblekage (90g)" },
    { date: "14. mar (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Høns i asparges", protein: "180g", sauce: "Asparges (100g)", carb: "Tarteletter (2 stk)", veg: "Persille (35g)", biret: "Sveskegrød (125g + 25g fløde)" },
    { date: "15. mar (Søn)", icon: "🐂", type: "Okse", dish: "Kalvesteg", protein: "80g Kød", sauce: "Sky (100g)", carb: "Kartofler (100g)", veg: "Waldorf (50g)", biret: "Citronfromage (90g)", isHoliday: true },
    { date: "16. mar (Man)", icon: "🐖", type: "Gris", dish: "Frikadeller", protein: "3 stk (30-40g)", sauce: "Brun sauce (100g)", carb: "Kartofler (100g)", veg: "Surkål (25g)", biret: "Blomkålssuppe (200g)" },
    { date: "17. mar (Tir)", icon: "🐔", type: "Fjerkræ", dish: "Kylling i Peberrod", protein: "180g Ret", sauce: "Peberrod (100g)", carb: "Kartofler (100g)", veg: "Gulerødder (50g)", biret: "Citronmåne (70g)" },
    { date: "18. mar (Ons)", icon: "🐟", type: "Fisk", dish: "Dampet Ørred", protein: "90g Fisk", sauce: "Urtecreme (80g)", carb: "Kartofler (100g)", veg: "Dild (35g)", biret: "Chokolademousse (80g)" },
    { date: "19. mar (Tor)", icon: "🥦", type: "Grøn", dish: "Ovnæggekage", protein: "150g Ret", sauce: "-", carb: "Rugbrød (1 stk)", veg: "Tomat (35g)", biret: "Minestronesuppe (200g)" },
    { date: "20. mar (Fre)", icon: "🐖", type: "Gris", dish: "Forloren Hare", protein: "80g Kød", sauce: "Vildt (100g)", carb: "Kartofler (100g)", veg: "Ribsgelé (25g)", biret: "Hindbærsnitte (60g)" },
    { date: "21. mar (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingelår BBQ", protein: "1 stk", sauce: "BBQ (80g)", carb: "Kartofler (100g)", veg: "Coleslaw (50g)", biret: "Abrikosgrød (125g + 25g fløde)" },
    { date: "22. mar (Søn)", icon: "🐂", type: "Okse", dish: "Oksesteg", protein: "80g Kød", sauce: "Rødvin (100g)", carb: "Flødekart. (100g + 40g fløde)", veg: "Perleløg (35g)", biret: "Ymerfromage (90g)", isHoliday: true },
    { date: "23. mar (Man)", icon: "🐖", type: "Gris", dish: "Boller i Karry", protein: "3 stk (30-40g)", sauce: "Karry (100g)", carb: "Ris (100g)", veg: "Chutney (25g)", biret: "Tomatsuppe (200g)" },
    { date: "24. mar (Tir)", icon: "🐖", type: "Gris", dish: "Karbonader", protein: "80g Kød", sauce: "Stuvede ærter (100g + 50g ærter)", carb: "Kartofler (100g)", veg: "Gulerødder (50g)", biret: "Budding (100g)" },
    { date: "25. mar (Ons)", icon: "🐟", type: "Fisk", dish: "Stegt Ørred (Vejle)", protein: "90g Fisk", sauce: "Persillesauce (80g)", carb: "Kartofler (100g)", veg: "Citron (35g)", biret: "Jordbærgrød (125g + 25g fløde)" },
    { date: "26. mar (Tor)", icon: "🥦", type: "Grøn", dish: "Broccoligratin", protein: "160g Ret", sauce: "-", carb: "Rugbrød (1 stk)", veg: "Gulerodssalat (30g)", biret: "Klar suppe (200g)" },
    { date: "27. mar (Fre)", icon: "🐔", type: "Fjerkræ", dish: "Kyllingefrikassé", protein: "180g Ret", sauce: "Frikassé (100g)", carb: "Kartofler (100g)", veg: "Grønt (50g)", biret: "Chokoladekage (70g)" },
    { date: "28. mar (Lør)", icon: "🐔", type: "Fjerkræ", dish: "Tarteletter m. høns", protein: "3 stk", sauce: "Asparges (100g)", carb: "Tarteletter", veg: "Tomat (35g)", biret: "Frugtsalat (100g)" },
    { date: "29. mar (Søn)", icon: "🐂", type: "Okse", dish: "PALMESØN: Lammekølle", protein: "80g Kød", sauce: "Sky (100g)", carb: "Flødekart. (100g + 40g fløde)", veg: "Bønner (50g)", biret: "Rabarbertrifli (90g)", isHoliday: true },
    { date: "30. mar (Man)", icon: "🐖", type: "Gris", dish: "Krebinet", protein: "80g Kød", sauce: "Stuvning (100g)", carb: "Kartofler (100g)", veg: "Persille (35g)", biret: "Aspargessuppe (200g)" },
    { date: "31. mar (Tir)", icon: "🐂", type: "Okse", dish: "Hakkebøf", protein: "80g Kød", sauce: "Bearnaise (80g)", carb: "Frites", veg: "Salat (30g)", biret: "Citronfromage (90g)" },
];
